// packages/preferences/vue/src/components/drawer/ShortcutKeysTab.vue
<script setup lang="ts">
/**
 * 快捷键设置标签页
 * @description 快捷键相关设置，显示快捷键组合
 */
import { computed, onMounted, ref } from 'vue';
import { usePreferences } from '../../composables';
import {
  DEFAULT_PREFERENCES,
  getShortcutKeys,
  isMacOs,
  getFeatureItemConfig,
  type LocaleMessages,
  type ShortcutKeysTabConfig,
  type ResolvedFeatureConfig,
} from '@admin-core/preferences';
import Block from './Block.vue';

const props = defineProps<{
  /** 当前语言包 */
  locale: LocaleMessages;
  /** UI 配置（控制功能项显示/禁用） */
  uiConfig?: ShortcutKeysTabConfig;
}>();

// ========== UI 配置解析（使用 computed 缓存） ==========
const getConfig = (blockKey: keyof ShortcutKeysTabConfig, itemKey?: string): ResolvedFeatureConfig =>
  getFeatureItemConfig(props.uiConfig, blockKey, itemKey);

// 缓存常用配置项
const configs = computed(() => ({
  shortcuts: getConfig('shortcuts'),
  enable: getConfig('shortcuts', 'enable'),
  globalPreferences: getConfig('shortcuts', 'globalPreferences'),
  globalSearch: getConfig('shortcuts', 'globalSearch'),
  globalLockScreen: getConfig('shortcuts', 'globalLockScreen'),
  globalLogout: getConfig('shortcuts', 'globalLogout'),
}));

const { preferences, setPreferences } = usePreferences();

// 默认值简写
const D = DEFAULT_PREFERENCES;

// 检测是否为 Mac 系统
const isMac = ref(false);
onMounted(() => {
  isMac.value = isMacOs();
});

// 获取快捷键按键列表
const getKeys = (key: string) => getShortcutKeys(key, isMac.value);

// ========== 快捷键设置 ==========
const shortcutKeysEnable = computed({
  get: () => preferences.value?.shortcutKeys.enable ?? D.shortcutKeys.enable,
  set: (value: boolean) => setPreferences({ shortcutKeys: { enable: value } }),
});

const globalPreferences = computed({
  get: () => preferences.value?.shortcutKeys.globalPreferences ?? D.shortcutKeys.globalPreferences,
  set: (value: boolean) => setPreferences({ shortcutKeys: { globalPreferences: value } }),
});

const globalSearch = computed({
  get: () => preferences.value?.shortcutKeys.globalSearch ?? D.shortcutKeys.globalSearch,
  set: (value: boolean) => setPreferences({ shortcutKeys: { globalSearch: value } }),
});

const globalLockScreen = computed({
  get: () => preferences.value?.shortcutKeys.globalLockScreen ?? D.shortcutKeys.globalLockScreen,
  set: (value: boolean) => setPreferences({ shortcutKeys: { globalLockScreen: value } }),
});

const globalLogout = computed({
  get: () => preferences.value?.shortcutKeys.globalLogout ?? D.shortcutKeys.globalLogout,
  set: (value: boolean) => setPreferences({ shortcutKeys: { globalLogout: value } }),
});

// 切换开关
const toggleEnable = () => { shortcutKeysEnable.value = !shortcutKeysEnable.value; };
const togglePreferences = () => { globalPreferences.value = !globalPreferences.value; };
const toggleSearch = () => { globalSearch.value = !globalSearch.value; };
const toggleLockScreen = () => { globalLockScreen.value = !globalLockScreen.value; };
const toggleLogout = () => { globalLogout.value = !globalLogout.value; };
</script>

<template>
  <Block v-if="configs.shortcuts.visible" :title="locale.shortcutKeys.title">
    <!-- 启用快捷键 - 主开关 -->
    <div
      v-if="configs.enable.visible"
      class="shortcut-item data-active:text-foreground data-active:font-semibold data-disabled:opacity-50 data-disabled:cursor-not-allowed data-disabled:[&_*]:cursor-not-allowed data-disabled:[&_.shortcut-item-label]:text-muted-foreground aria-checked:text-foreground"
      :class="{ disabled: configs.enable.disabled }"
      role="switch"
      :aria-checked="shortcutKeysEnable"
      :aria-disabled="configs.enable.disabled"
      :data-state="shortcutKeysEnable ? 'active' : 'inactive'"
      :data-disabled="configs.enable.disabled ? 'true' : undefined"
      :tabindex="configs.enable.disabled ? -1 : 0"
      @click="!configs.enable.disabled && toggleEnable()"
      @keydown.enter.space.prevent="!configs.enable.disabled && toggleEnable()"
    >
      <span class="shortcut-item-label">{{ locale.shortcutKeys.enable }}</span>
      <div class="shortcut-item-right">
        <div
          class="preferences-switch data-checked:border-primary data-checked:ring-1 data-checked:ring-ring/30"
          :class="{ checked: shortcutKeysEnable }"
          :data-state="shortcutKeysEnable ? 'checked' : 'unchecked'"
          :data-disabled="configs.enable.disabled ? 'true' : undefined"
        >
          <span class="preferences-switch-thumb" />
        </div>
      </div>
    </div>

    <!-- 打开设置 -->
    <div
      v-if="configs.globalPreferences.visible"
      class="shortcut-item data-active:text-foreground data-active:font-semibold data-disabled:opacity-50 data-disabled:cursor-not-allowed data-disabled:[&_*]:cursor-not-allowed data-disabled:[&_.shortcut-item-label]:text-muted-foreground aria-checked:text-foreground"
      :class="{ disabled: !shortcutKeysEnable || configs.globalPreferences.disabled }"
      role="switch"
      :aria-checked="globalPreferences"
      :aria-disabled="!shortcutKeysEnable || configs.globalPreferences.disabled"
      :data-state="globalPreferences ? 'active' : 'inactive'"
      :data-disabled="(!shortcutKeysEnable || configs.globalPreferences.disabled) ? 'true' : undefined"
      :tabindex="shortcutKeysEnable && !configs.globalPreferences.disabled ? 0 : -1"
      @click="shortcutKeysEnable && !configs.globalPreferences.disabled && togglePreferences()"
      @keydown.enter.space.prevent="shortcutKeysEnable && !configs.globalPreferences.disabled && togglePreferences()"
    >
      <span class="shortcut-item-label">{{ locale.shortcutKeys.globalPreferences }}</span>
      <div class="shortcut-item-right">
        <div class="shortcut-keys">
          <kbd v-for="k in getKeys('globalPreferences')" :key="k" class="shortcut-key">{{ k }}</kbd>
        </div>
        <div
          class="preferences-switch data-checked:border-primary data-checked:ring-1 data-checked:ring-ring/30"
          :class="{ checked: globalPreferences }"
          :data-state="globalPreferences ? 'checked' : 'unchecked'"
          :data-disabled="(!shortcutKeysEnable || configs.globalPreferences.disabled) ? 'true' : undefined"
        >
          <span class="preferences-switch-thumb" />
        </div>
      </div>
    </div>

    <!-- 全局搜索 -->
    <div
      v-if="configs.globalSearch.visible"
      class="shortcut-item data-active:text-foreground data-active:font-semibold data-disabled:opacity-50 data-disabled:cursor-not-allowed data-disabled:[&_*]:cursor-not-allowed data-disabled:[&_.shortcut-item-label]:text-muted-foreground aria-checked:text-foreground"
      :class="{ disabled: !shortcutKeysEnable || configs.globalSearch.disabled }"
      role="switch"
      :aria-checked="globalSearch"
      :aria-disabled="!shortcutKeysEnable || configs.globalSearch.disabled"
      :data-state="globalSearch ? 'active' : 'inactive'"
      :data-disabled="(!shortcutKeysEnable || configs.globalSearch.disabled) ? 'true' : undefined"
      :tabindex="shortcutKeysEnable && !configs.globalSearch.disabled ? 0 : -1"
      @click="shortcutKeysEnable && !configs.globalSearch.disabled && toggleSearch()"
      @keydown.enter.space.prevent="shortcutKeysEnable && !configs.globalSearch.disabled && toggleSearch()"
    >
      <span class="shortcut-item-label">{{ locale.shortcutKeys.globalSearch }}</span>
      <div class="shortcut-item-right">
        <div class="shortcut-keys">
          <kbd v-for="k in getKeys('globalSearch')" :key="k" class="shortcut-key">{{ k }}</kbd>
        </div>
        <div
          class="preferences-switch data-checked:border-primary data-checked:ring-1 data-checked:ring-ring/30"
          :class="{ checked: globalSearch }"
          :data-state="globalSearch ? 'checked' : 'unchecked'"
          :data-disabled="(!shortcutKeysEnable || configs.globalSearch.disabled) ? 'true' : undefined"
        >
          <span class="preferences-switch-thumb" />
        </div>
      </div>
    </div>

    <!-- 锁屏 -->
    <div
      v-if="configs.globalLockScreen.visible"
      class="shortcut-item data-active:text-foreground data-active:font-semibold data-disabled:opacity-50 data-disabled:cursor-not-allowed data-disabled:[&_*]:cursor-not-allowed data-disabled:[&_.shortcut-item-label]:text-muted-foreground aria-checked:text-foreground"
      :class="{ disabled: !shortcutKeysEnable || configs.globalLockScreen.disabled }"
      role="switch"
      :aria-checked="globalLockScreen"
      :aria-disabled="!shortcutKeysEnable || configs.globalLockScreen.disabled"
      :data-state="globalLockScreen ? 'active' : 'inactive'"
      :data-disabled="(!shortcutKeysEnable || configs.globalLockScreen.disabled) ? 'true' : undefined"
      :tabindex="shortcutKeysEnable && !configs.globalLockScreen.disabled ? 0 : -1"
      @click="shortcutKeysEnable && !configs.globalLockScreen.disabled && toggleLockScreen()"
      @keydown.enter.space.prevent="shortcutKeysEnable && !configs.globalLockScreen.disabled && toggleLockScreen()"
    >
      <span class="shortcut-item-label">{{ locale.shortcutKeys.globalLockScreen }}</span>
      <div class="shortcut-item-right">
        <div class="shortcut-keys">
          <kbd v-for="k in getKeys('globalLockScreen')" :key="k" class="shortcut-key">{{ k }}</kbd>
        </div>
        <div
          class="preferences-switch data-checked:border-primary data-checked:ring-1 data-checked:ring-ring/30"
          :class="{ checked: globalLockScreen }"
          :data-state="globalLockScreen ? 'checked' : 'unchecked'"
          :data-disabled="(!shortcutKeysEnable || configs.globalLockScreen.disabled) ? 'true' : undefined"
        >
          <span class="preferences-switch-thumb" />
        </div>
      </div>
    </div>

    <!-- 登出 -->
    <div
      v-if="configs.globalLogout.visible"
      class="shortcut-item data-active:text-foreground data-active:font-semibold data-disabled:opacity-50 data-disabled:cursor-not-allowed data-disabled:[&_*]:cursor-not-allowed data-disabled:[&_.shortcut-item-label]:text-muted-foreground aria-checked:text-foreground"
      :class="{ disabled: !shortcutKeysEnable || configs.globalLogout.disabled }"
      role="switch"
      :aria-checked="globalLogout"
      :aria-disabled="!shortcutKeysEnable || configs.globalLogout.disabled"
      :data-state="globalLogout ? 'active' : 'inactive'"
      :data-disabled="(!shortcutKeysEnable || configs.globalLogout.disabled) ? 'true' : undefined"
      :tabindex="shortcutKeysEnable && !configs.globalLogout.disabled ? 0 : -1"
      @click="shortcutKeysEnable && !configs.globalLogout.disabled && toggleLogout()"
      @keydown.enter.space.prevent="shortcutKeysEnable && !configs.globalLogout.disabled && toggleLogout()"
    >
      <span class="shortcut-item-label">{{ locale.shortcutKeys.globalLogout }}</span>
      <div class="shortcut-item-right">
        <div class="shortcut-keys">
          <kbd v-for="k in getKeys('globalLogout')" :key="k" class="shortcut-key">{{ k }}</kbd>
        </div>
        <div
          class="preferences-switch data-checked:border-primary data-checked:ring-1 data-checked:ring-ring/30"
          :class="{ checked: globalLogout }"
          :data-state="globalLogout ? 'checked' : 'unchecked'"
          :data-disabled="(!shortcutKeysEnable || configs.globalLogout.disabled) ? 'true' : undefined"
        >
          <span class="preferences-switch-thumb" />
        </div>
      </div>
    </div>
  </Block>
</template>

// packages/preferences/react/src/components/drawer/ShortcutKeysTab.tsx
/**
 * 快捷键设置标签页
 * @description 全局快捷键、搜索、锁屏等设置，显示快捷键组合
 */
import { 
  getShortcutKeys, 
  isMacOs, 
  getFeatureItemConfig,
  type LocaleMessages,
  type ShortcutKeysTabConfig,
  type ResolvedFeatureConfig,
} from '@admin-core/preferences';
import React, { memo, useCallback, useMemo } from 'react';
import { usePreferences } from '../../hooks';
import { Block } from './Block';

export interface ShortcutKeysTabProps {
  /** 当前语言包 */
  locale: LocaleMessages;
  /** UI 配置（控制功能项显示/禁用） */
  uiConfig?: ShortcutKeysTabConfig;
}

interface ShortcutItemProps {
  label: string;
  shortcutKeys?: string[];
  checked: boolean;
  onChange: () => void;
  disabled?: boolean;
}

const ShortcutItem = memo<ShortcutItemProps>(function ShortcutItem({
  label,
  shortcutKeys,
  checked,
  onChange,
  disabled = false,
}) {
  const handleClick = useCallback(() => {
    if (!disabled) onChange();
  }, [disabled, onChange]);

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (disabled) return;
      if (e.key === ' ' || e.key === 'Enter') {
        e.preventDefault();
        onChange();
      }
    },
    [disabled, onChange]
  );

  return (
    <div
      className={`shortcut-item data-active:text-foreground data-active:font-semibold data-disabled:opacity-50 data-disabled:cursor-not-allowed data-disabled:[&_*]:cursor-not-allowed data-disabled:[&_.shortcut-item-label]:text-muted-foreground aria-checked:text-foreground ${disabled ? 'disabled' : ''}`}
      role="switch"
      aria-checked={checked}
      aria-disabled={disabled}
      data-state={checked ? 'active' : 'inactive'}
      data-disabled={disabled ? 'true' : undefined}
      tabIndex={disabled ? -1 : 0}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
    >
      <span className="shortcut-item-label">{label}</span>
      <div className="shortcut-item-right">
        {shortcutKeys && shortcutKeys.length > 0 && (
          <div className="shortcut-keys">
            {shortcutKeys.map((key) => (
              <kbd key={key} className="shortcut-key">{key}</kbd>
            ))}
          </div>
        )}
        <div
          className={`preferences-switch data-checked:border-primary data-checked:ring-1 data-checked:ring-ring/30 ${checked ? 'checked' : ''}`}
          data-state={checked ? 'checked' : 'unchecked'}
          data-disabled={disabled ? 'true' : undefined}
        >
          <span className="preferences-switch-thumb" />
        </div>
      </div>
    </div>
  );
});

export const ShortcutKeysTab: React.FC<ShortcutKeysTabProps> = memo(({ locale, uiConfig }) => {
  const { preferences, setPreferences } = usePreferences();

  // ========== UI 配置解析（使用 useMemo 缓存） ==========
  const getConfig = useCallback(
    (blockKey: keyof ShortcutKeysTabConfig, itemKey?: string): ResolvedFeatureConfig =>
      getFeatureItemConfig(uiConfig, blockKey, itemKey),
    [uiConfig]
  );

  // 缓存常用配置项
  const configs = useMemo(() => ({
    shortcuts: getConfig('shortcuts'),
    enable: getConfig('shortcuts', 'enable'),
    globalPreferences: getConfig('shortcuts', 'globalPreferences'),
    globalSearch: getConfig('shortcuts', 'globalSearch'),
    globalLockScreen: getConfig('shortcuts', 'globalLockScreen'),
    globalLogout: getConfig('shortcuts', 'globalLogout'),
  }), [getConfig]);

  // 检测是否为 Mac 系统
  const isMac = useMemo(() => isMacOs(), []);

  // 获取快捷键按键列表
  const getKeys = useCallback(
    (key: string) => getShortcutKeys(key, isMac),
    [isMac]
  );

  // ========== 稳定的回调函数（使用 ref 获取最新值，避免依赖变化导致重渲染） ==========
  const preferencesRef = React.useRef(preferences);
  
  // 在 useEffect 中更新 ref，避免在渲染期间产生副作用
  React.useEffect(() => {
    preferencesRef.current = preferences;
  });
  
  const handleToggleEnable = useCallback(() => {
    setPreferences({ shortcutKeys: { enable: !preferencesRef.current.shortcutKeys.enable } });
  }, [setPreferences]);

  const handleToggleGlobalPreferences = useCallback(() => {
    setPreferences({ shortcutKeys: { globalPreferences: !preferencesRef.current.shortcutKeys.globalPreferences } });
  }, [setPreferences]);

  const handleToggleGlobalSearch = useCallback(() => {
    setPreferences({ shortcutKeys: { globalSearch: !preferencesRef.current.shortcutKeys.globalSearch } });
  }, [setPreferences]);

  const handleToggleGlobalLockScreen = useCallback(() => {
    setPreferences({ shortcutKeys: { globalLockScreen: !preferencesRef.current.shortcutKeys.globalLockScreen } });
  }, [setPreferences]);

  const handleToggleGlobalLogout = useCallback(() => {
    setPreferences({ shortcutKeys: { globalLogout: !preferencesRef.current.shortcutKeys.globalLogout } });
  }, [setPreferences]);

  const isEnabled = preferences.shortcutKeys.enable;

  if (!configs.shortcuts.visible) {
    return null;
  }

  return (
    <Block title={locale.shortcutKeys.title}>
      {/* 启用快捷键 - 主开关 */}
      {configs.enable.visible && (
        <ShortcutItem
          label={locale.shortcutKeys.enable}
          checked={isEnabled}
          onChange={handleToggleEnable}
          disabled={configs.enable.disabled}
        />
      )}

      {/* 打开设置 */}
      {configs.globalPreferences.visible && (
        <ShortcutItem
          label={locale.shortcutKeys.globalPreferences}
          shortcutKeys={getKeys('globalPreferences')}
          checked={preferences.shortcutKeys.globalPreferences}
          onChange={handleToggleGlobalPreferences}
          disabled={!isEnabled || configs.globalPreferences.disabled}
        />
      )}

      {/* 全局搜索 */}
      {configs.globalSearch.visible && (
        <ShortcutItem
          label={locale.shortcutKeys.globalSearch}
          shortcutKeys={getKeys('globalSearch')}
          checked={preferences.shortcutKeys.globalSearch}
          onChange={handleToggleGlobalSearch}
          disabled={!isEnabled || configs.globalSearch.disabled}
        />
      )}

      {/* 锁屏 */}
      {configs.globalLockScreen.visible && (
        <ShortcutItem
          label={locale.shortcutKeys.globalLockScreen}
          shortcutKeys={getKeys('globalLockScreen')}
          checked={preferences.shortcutKeys.globalLockScreen}
          onChange={handleToggleGlobalLockScreen}
          disabled={!isEnabled || configs.globalLockScreen.disabled}
        />
      )}

      {/* 登出 */}
      {configs.globalLogout.visible && (
        <ShortcutItem
          label={locale.shortcutKeys.globalLogout}
          shortcutKeys={getKeys('globalLogout')}
          checked={preferences.shortcutKeys.globalLogout}
          onChange={handleToggleGlobalLogout}
          disabled={!isEnabled || configs.globalLogout.disabled}
        />
      )}
    </Block>
  );
});

ShortcutKeysTab.displayName = 'ShortcutKeysTab';

export default ShortcutKeysTab;
