// packages/preferences/vue/src/components/drawer/TransitionPreview.vue
<script setup lang="ts">
/**
 * 动画预览组件
 * @description 实时展示页面切换动画效果
 */
import { ref, watch, onMounted, onUnmounted, computed } from 'vue';
import type { PageTransitionType } from '@admin-core/preferences';

const props = withDefaults(defineProps<{
  /** 当前选中的动画类型 */
  transition: PageTransitionType;
  /** 是否启用动画（全局开关） */
  enabled?: boolean;
  /** 是否选中（只有选中时才播放动画） */
  active?: boolean;
  /** 紧凑模式（用于网格展示） */
  compact?: boolean;
}>(), {
  enabled: true,
  active: false,
  compact: false,
});

// 是否应该播放动画：全局开启 且 当前选中
const shouldAnimate = computed(() => props.enabled && props.active);

// 动画状态（使用 ref 存储定时器，避免多实例冲突）
const isAnimating = ref(false);
const showContent = ref(true);
const animationTimerRef = ref<ReturnType<typeof setTimeout> | null>(null);
const loopTimerRef = ref<ReturnType<typeof setInterval> | null>(null);

// 动画 CSS 类映射
const transitionClasses: Record<PageTransitionType, { enter: string; leave: string }> = {
  'fade': {
    enter: 'transition-preview-fade-enter',
    leave: 'transition-preview-fade-leave',
  },
  'fade-slide': {
    enter: 'transition-preview-fade-slide-enter',
    leave: 'transition-preview-fade-slide-leave',
  },
  'fade-up': {
    enter: 'transition-preview-fade-up-enter',
    leave: 'transition-preview-fade-up-leave',
  },
  'fade-down': {
    enter: 'transition-preview-fade-down-enter',
    leave: 'transition-preview-fade-down-leave',
  },
  'slide-left': {
    enter: 'transition-preview-slide-left-enter',
    leave: 'transition-preview-slide-left-leave',
  },
  'slide-right': {
    enter: 'transition-preview-slide-right-enter',
    leave: 'transition-preview-slide-right-leave',
  },
};

// 当前动画类
const currentClass = ref('');

// 动画时长配置（毫秒）
const ANIMATION_DURATION = 500; // CSS 动画时长
const ANIMATION_GAP = 150;      // 切换间隔
const LOOP_INTERVAL = 3500;     // 循环间隔

// 清理单个定时器
const clearAnimationTimer = () => {
  if (animationTimerRef.value) {
    clearTimeout(animationTimerRef.value);
    animationTimerRef.value = null;
  }
};

// 设置定时器（先清理再设置）
const setAnimationTimer = (callback: () => void, delay: number) => {
  clearAnimationTimer();
  animationTimerRef.value = setTimeout(callback, delay);
};

// 播放动画
const playAnimation = () => {
  if (!shouldAnimate.value || isAnimating.value) return;
  
  isAnimating.value = true;
  const classes = transitionClasses[props.transition] || transitionClasses['fade'];
  
  // 使用 requestAnimationFrame 确保流畅
  requestAnimationFrame(() => {
    // 离开动画
    currentClass.value = classes.leave;
    
    setAnimationTimer(() => {
      showContent.value = false;
      currentClass.value = '';
      
      // 短暂延迟后显示新内容
      setAnimationTimer(() => {
        requestAnimationFrame(() => {
          showContent.value = true;
          currentClass.value = classes.enter;
          
          // 动画结束后重置
          setAnimationTimer(() => {
            currentClass.value = '';
            isAnimating.value = false;
          }, ANIMATION_DURATION);
        });
      }, ANIMATION_GAP);
    }, ANIMATION_DURATION);
  });
};

// 自动循环播放
const startLoop = () => {
  stopLoop();
  if (shouldAnimate.value) {
    // 延迟启动，避免同时触发多个动画
    setAnimationTimer(() => {
      playAnimation();
      loopTimerRef.value = setInterval(playAnimation, LOOP_INTERVAL);
    }, 300);
  }
};

const stopLoop = () => {
  if (loopTimerRef.value) {
    clearInterval(loopTimerRef.value);
    loopTimerRef.value = null;
  }
  if (animationTimerRef.value) {
    clearTimeout(animationTimerRef.value);
    animationTimerRef.value = null;
  }
  isAnimating.value = false;
};

let visibilityHandler: (() => void) | null = null;

// 监听是否应该播放动画
watch(shouldAnimate, (should) => {
  if (!should) {
    stopLoop();
    showContent.value = true;
    currentClass.value = '';
    return;
  }
  if (typeof document !== 'undefined' && document.visibilityState === 'hidden') {
    stopLoop();
    showContent.value = true;
    currentClass.value = '';
    return;
  }
  startLoop();
}, { immediate: true });

onMounted(() => {
  if (typeof document === 'undefined') return;
  visibilityHandler = () => {
    if (document.visibilityState === 'hidden') {
      stopLoop();
      showContent.value = true;
      currentClass.value = '';
    } else if (shouldAnimate.value) {
      startLoop();
    }
  };
  document.addEventListener('visibilitychange', visibilityHandler);
});

onUnmounted(() => {
  if (visibilityHandler) {
    document.removeEventListener('visibilitychange', visibilityHandler);
    visibilityHandler = null;
  }
  stopLoop();
});
</script>

<template>
  <div
    class="transition-preview pref-disabled"
    :class="{ disabled: !enabled, compact: compact }"
    :data-disabled="!enabled ? 'true' : undefined"
  >
    <div class="transition-preview-screen">
      <!-- 模拟页面头部 -->
      <div class="transition-preview-header">
        <div class="transition-preview-header-dot" />
        <div class="transition-preview-header-dot" />
        <div class="transition-preview-header-dot" />
      </div>
      <!-- 模拟侧边栏 -->
      <div class="transition-preview-sidebar">
        <div class="transition-preview-menu-item active" data-state="active" />
        <div class="transition-preview-menu-item" />
        <div class="transition-preview-menu-item" />
      </div>
      <!-- 模拟内容区 -->
      <div class="transition-preview-content">
        <div 
          v-if="showContent" 
          class="transition-preview-page"
          :class="currentClass"
        >
          <div class="transition-preview-card" />
          <div class="transition-preview-card small" />
        </div>
      </div>
    </div>
  </div>
</template>

// packages/preferences/react/src/components/drawer/TransitionPreview.tsx
/**
 * 动画预览组件
 * @description 实时展示页面切换动画效果
 */
import React, { memo, useState, useEffect, useRef, useCallback, useMemo } from 'react';
import type { PageTransitionType } from '@admin-core/preferences';

export interface TransitionPreviewProps {
  /** 当前选中的动画类型 */
  transition: PageTransitionType;
  /** 是否启用动画（全局开关） */
  enabled?: boolean;
  /** 是否选中（只有选中时才播放动画） */
  active?: boolean;
  /** 紧凑模式（用于网格展示） */
  compact?: boolean;
}

// 动画 CSS 类映射
const transitionClasses: Record<PageTransitionType, { enter: string; leave: string }> = {
  'fade': {
    enter: 'transition-preview-fade-enter',
    leave: 'transition-preview-fade-leave',
  },
  'fade-slide': {
    enter: 'transition-preview-fade-slide-enter',
    leave: 'transition-preview-fade-slide-leave',
  },
  'fade-up': {
    enter: 'transition-preview-fade-up-enter',
    leave: 'transition-preview-fade-up-leave',
  },
  'fade-down': {
    enter: 'transition-preview-fade-down-enter',
    leave: 'transition-preview-fade-down-leave',
  },
  'slide-left': {
    enter: 'transition-preview-slide-left-enter',
    leave: 'transition-preview-slide-left-leave',
  },
  'slide-right': {
    enter: 'transition-preview-slide-right-enter',
    leave: 'transition-preview-slide-right-leave',
  },
};

// 动画时长配置（毫秒）
const ANIMATION_DURATION = 500; // CSS 动画时长
const ANIMATION_GAP = 150;      // 切换间隔
const LOOP_INTERVAL = 3500;     // 循环间隔

export const TransitionPreview: React.FC<TransitionPreviewProps> = memo(({ 
  transition, 
  enabled = true,
  active = false,
  compact = false,
}) => {
  const [showContent, setShowContent] = useState(true);
  const [currentClass, setCurrentClass] = useState('');
  const isAnimatingRef = useRef(false);
  const timersRef = useRef<ReturnType<typeof setTimeout>[]>([]);
  const loopIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // 是否应该播放动画：全局开启 且 当前选中
  const shouldAnimate = useMemo(() => enabled && active, [enabled, active]);

  const clearTimers = useCallback(() => {
    timersRef.current.forEach(clearTimeout);
    timersRef.current = [];
    if (loopIntervalRef.current) {
      clearInterval(loopIntervalRef.current);
      loopIntervalRef.current = null;
    }
    isAnimatingRef.current = false;
  }, []);

  const resetAnimationState = useCallback(() => {
    setShowContent(true);
    setCurrentClass('');
  }, []);

  const playAnimation = useCallback(() => {
    if (!shouldAnimate || isAnimatingRef.current) return;
    
    isAnimatingRef.current = true;
    const classes = transitionClasses[transition] || transitionClasses['fade'];
    
    // 使用 requestAnimationFrame 确保流畅
    requestAnimationFrame(() => {
      // 离开动画
      setCurrentClass(classes.leave);
      
      const timer1 = setTimeout(() => {
        setShowContent(false);
        setCurrentClass('');
        
        // 短暂延迟后显示新内容
        const timer2 = setTimeout(() => {
          requestAnimationFrame(() => {
            setShowContent(true);
            setCurrentClass(classes.enter);
            
            // 动画结束后重置
            const timer3 = setTimeout(() => {
              setCurrentClass('');
              isAnimatingRef.current = false;
            }, ANIMATION_DURATION);
            timersRef.current.push(timer3);
          });
        }, ANIMATION_GAP);
        timersRef.current.push(timer2);
      }, ANIMATION_DURATION);
      timersRef.current.push(timer1);
    });
  }, [shouldAnimate, transition]);

  const startLoop = useCallback(() => {
    if (!shouldAnimate) return;
    clearTimers();
    resetAnimationState();
    const initialTimer = setTimeout(() => {
      playAnimation();
      loopIntervalRef.current = setInterval(playAnimation, LOOP_INTERVAL);
    }, 300);
    timersRef.current.push(initialTimer);
  }, [shouldAnimate, playAnimation, clearTimers, resetAnimationState]);

  const stopLoop = useCallback(() => {
    clearTimers();
    resetAnimationState();
  }, [clearTimers, resetAnimationState]);

  // 自动循环播放
  useEffect(() => {
    if (!shouldAnimate) {
      stopLoop();
      return;
    }
    if (typeof document !== 'undefined' && document.visibilityState === 'hidden') {
      stopLoop();
      return;
    }
    startLoop();
    return clearTimers;
  }, [shouldAnimate, startLoop, stopLoop, clearTimers]);

  // 页面不可见时暂停动画
  useEffect(() => {
    if (typeof document === 'undefined') return;
    const handleVisibilityChange = () => {
      if (document.visibilityState === 'hidden') {
        stopLoop();
      } else if (shouldAnimate) {
        startLoop();
      }
    };
    document.addEventListener('visibilitychange', handleVisibilityChange);
    return () => document.removeEventListener('visibilitychange', handleVisibilityChange);
  }, [shouldAnimate, startLoop, stopLoop]);

  const classNames = (() => {
    const classes = ['transition-preview', 'pref-disabled'];
    if (!enabled) classes.push('disabled');
    if (compact) classes.push('compact');
    return classes.join(' ');
  })();

  return (
    <div className={classNames} data-disabled={!enabled ? 'true' : undefined}>
      <div className="transition-preview-screen">
        {/* 模拟页面头部 */}
        <div className="transition-preview-header">
          <div className="transition-preview-header-dot" />
          <div className="transition-preview-header-dot" />
          <div className="transition-preview-header-dot" />
        </div>
        {/* 模拟侧边栏 */}
        <div className="transition-preview-sidebar">
          <div className="transition-preview-menu-item active" data-state="active" />
          <div className="transition-preview-menu-item" />
          <div className="transition-preview-menu-item" />
        </div>
        {/* 模拟内容区 */}
        <div className="transition-preview-content">
          {showContent && (
            <div className={`transition-preview-page ${currentClass}`}>
              <div className="transition-preview-card" />
              <div className="transition-preview-card small" />
            </div>
          )}
        </div>
      </div>
    </div>
  );
});

TransitionPreview.displayName = 'TransitionPreview';

export default TransitionPreview;
