// packages/preferences/react/src/components/drawer/SwitchItem.tsx
/**
 * 开关设置项组件
 * @description 与 Vue 版本保持一致的 API 设计
 */
import { memo, useCallback, useId } from 'react';

export interface SwitchItemProps {
  /** 标签文本 */
  label: string;
  /** 图标 SVG 字符串 */
  icon?: string;
  /** 是否选中 */
  checked: boolean;
  /** 变更回调 */
  onChange: (checked: boolean) => void;
  /** 是否禁用 */
  disabled?: boolean;
  /** 提示文本 */
  tip?: string;
}

/**
 * 开关组件 - 使用 memo 优化重渲染
 * @description 增强无障碍性，支持键盘操作
 */
export const SwitchItem = memo<SwitchItemProps>(function SwitchItem({
  label,
  icon,
  checked,
  onChange,
  disabled = false,
  tip,
}) {
  const switchId = useId();

  const handleClick = useCallback(() => {
    if (!disabled) {
      onChange(!checked);
    }
  }, [disabled, checked, onChange]);

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (disabled) return;
      // 空格或回车触发切换
      if (e.key === ' ' || e.key === 'Enter') {
        e.preventDefault();
        onChange(!checked);
      }
    },
    [disabled, checked, onChange]
  );

  return (
    <div
      className={`switch-item ${disabled ? 'disabled' : ''}`}
      data-disabled={disabled ? 'true' : undefined}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
      title={tip}
      role="switch"
      aria-checked={checked}
      aria-disabled={disabled}
      aria-labelledby={`${switchId}-label`}
      tabIndex={disabled ? -1 : 0}
    >
      <span id={`${switchId}-label`} className="switch-item-label">
        {icon && <span className="switch-item-icon" dangerouslySetInnerHTML={{ __html: icon }} />}
        {label}
      </span>
      <div
        className={`preferences-switch data-checked:border-primary data-checked:ring-1 data-checked:ring-ring/30 ${checked ? 'checked' : ''}`}
        data-state={checked ? 'checked' : 'unchecked'}
        aria-hidden="true"
      >
        <span className="preferences-switch-thumb" />
      </div>
    </div>
  );
});

export default SwitchItem;

// packages/preferences/vue/src/components/drawer/SwitchItem.vue
<script setup lang="ts">
/**
 * 开关设置项组件
 * @description 与 React 版本保持一致的 API 设计，增强无障碍性
 */

const props = defineProps<{
  /** 标签文本 */
  label: string;
  /** 图标 SVG 字符串 */
  icon?: string;
  /** 是否禁用 */
  disabled?: boolean;
  /** 提示文本 */
  tip?: string;
}>();

const checked = defineModel<boolean>({ default: false });

// 生成唯一 ID（在 setup 中生成一次，保持稳定）
const switchId = `switch-${Math.random().toString(36).slice(2, 9)}`;

const toggle = () => {
  if (!props.disabled) {
    checked.value = !checked.value;
  }
};

const handleKeyDown = (e: KeyboardEvent) => {
  if (props.disabled) return;
  // 空格或回车触发切换
  if (e.key === ' ' || e.key === 'Enter') {
    e.preventDefault();
    checked.value = !checked.value;
  }
};
</script>

<template>
  <div
    class="switch-item"
    :class="{ disabled }"
    :data-disabled="disabled ? 'true' : undefined"
    :title="tip"
    role="switch"
    :aria-checked="checked"
    :aria-disabled="disabled"
    :aria-labelledby="`${switchId}-label`"
    :tabindex="disabled ? -1 : 0"
    @click="toggle"
    @keydown="handleKeyDown"
  >
    <span :id="`${switchId}-label`" class="switch-item-label">
      <span v-if="icon" class="switch-item-icon" v-html="icon" />
      {{ label }}
    </span>
    <div
      class="preferences-switch data-checked:border-primary data-checked:ring-1 data-checked:ring-ring/30"
      :class="{ checked: checked }"
      :data-state="checked ? 'checked' : 'unchecked'"
      aria-hidden="true"
    >
      <span class="preferences-switch-thumb" />
    </div>
  </div>
</template>
