// packages/layout/vue/src/components/widgets/GlobalSearch.vue
<script setup lang="ts">
/**
 * 全局搜索组件
 * @description 全局菜单搜索导航，支持快捷键 Ctrl+K
 */
import { computed, ref, watch, onMounted, onUnmounted, nextTick } from 'vue';
import { useLayoutContext } from '../../composables';
import type { MenuItem } from '@admin-core/layout';

interface SearchMenuItem extends MenuItem {
  parentPath?: string[];
  searchText: string;
}

const context = useLayoutContext();

// 搜索框状态
const isOpen = ref(false);
const keyword = ref('');
const selectedIndex = ref(0);
const scrollTop = ref(0);
const inputRef = ref<HTMLInputElement | null>(null);
const resultListRef = ref<HTMLDivElement | null>(null);

// 菜单数据
const menus = computed(() => context.props.menus || []);

// 扁平化菜单（用于搜索）
const flatMenus = computed<SearchMenuItem[]>(() => {
  if (!isOpen.value) return [];
  const result: SearchMenuItem[] = [];
  
  const flatten = (items: MenuItem[], parentPath: string[] = []) => {
    for (const item of items) {
      const currentPath = [...parentPath, item.name];
      
      // 只添加有路径的菜单项
      if (item.path && !item.hidden) {
        const name = item.name || '';
        const path = item.path || '';
        result.push({
          ...item,
          searchText: `${name} ${path}`.toLowerCase(),
          parentPath: parentPath.length > 0 ? parentPath : undefined,
        });
      }
      
      // 递归处理子菜单
      if (item.children?.length) {
        flatten(item.children, currentPath);
      }
    }
  };
  
  flatten(menus.value);
  return result;
});

// 搜索结果
const MAX_RESULTS = 200;
const searchResults = computed(() => {
  const query = keyword.value.trim().toLowerCase();
  if (!query) return [];

  const results: SearchMenuItem[] = [];
  for (const item of flatMenus.value) {
    if (item.searchText.includes(query)) {
      results.push(item);
      if (results.length >= MAX_RESULTS) break;
    }
  }
  return results;
});

const itemHeight = ref(56);
const listResizeObserver = ref<ResizeObserver | null>(null);
const RESULT_MAX_HEIGHT = 320;
const RESULT_OVERSCAN = 4;
const totalHeight = computed(() => searchResults.value.length * itemHeight.value);
const viewportHeight = computed(() =>
  totalHeight.value === 0 ? RESULT_MAX_HEIGHT : Math.min(totalHeight.value, RESULT_MAX_HEIGHT)
);
const startIndex = computed(() =>
  Math.max(0, Math.floor(scrollTop.value / itemHeight.value) - RESULT_OVERSCAN)
);
const endIndex = computed(() =>
  Math.min(
    searchResults.value.length,
    Math.ceil((scrollTop.value + viewportHeight.value) / itemHeight.value) + RESULT_OVERSCAN
  )
);
const visibleResults = computed(() =>
  searchResults.value.slice(startIndex.value, endIndex.value)
);

watch(
  [isOpen, totalHeight, viewportHeight, scrollTop],
  ([open, total, viewHeight, currentTop]) => {
    if (!open) return;
    const maxScrollTop = Math.max(0, total - viewHeight);
    if (currentTop <= maxScrollTop) return;
    const nextTop = Math.max(0, maxScrollTop);
    if (resultListRef.value) {
      resultListRef.value.scrollTop = nextTop;
    }
    if (scrollTop.value !== nextTop) {
      scrollTop.value = nextTop;
    }
  }
);

// 打开搜索框
const openSearch = () => {
  isOpen.value = true;
  keyword.value = '';
  selectedIndex.value = 0;
  nextTick(() => {
    inputRef.value?.focus();
  });
};

// 关闭搜索框
const closeSearch = () => {
  isOpen.value = false;
  keyword.value = '';
  selectedIndex.value = 0;
};

// 选择菜单项
const selectItem = (item: MenuItem) => {
  if (item.path) {
    context.events.onGlobalSearch?.(item.path);
    
    // 如果有路由配置，进行导航
    if (context.props.router?.navigate) {
      context.props.router.navigate(item.path);
    }
  }
  closeSearch();
};

const handleResultClick = (e: MouseEvent) => {
  const index = Number((e.currentTarget as HTMLElement | null)?.dataset?.index);
  if (Number.isNaN(index)) return;
  const item = searchResults.value[index];
  if (item) selectItem(item);
};

const handleResultMouseEnter = (e: MouseEvent) => {
  const index = Number((e.currentTarget as HTMLElement | null)?.dataset?.index);
  if (Number.isNaN(index)) return;
  selectedIndex.value = index;
};

// 键盘导航
const handleKeydown = (e: KeyboardEvent) => {
  switch (e.key) {
    case 'ArrowDown':
      e.preventDefault();
      if (selectedIndex.value < searchResults.value.length - 1) {
        selectedIndex.value++;
        scrollToSelected();
      }
      break;
    case 'ArrowUp':
      e.preventDefault();
      if (selectedIndex.value > 0) {
        selectedIndex.value--;
        scrollToSelected();
      }
      break;
    case 'Enter':
      e.preventDefault();
      if (searchResults.value[selectedIndex.value]) {
        selectItem(searchResults.value[selectedIndex.value]);
      }
      break;
    case 'Escape':
      e.preventDefault();
      closeSearch();
      break;
  }
};

// 滚动到选中项
const ensureIndexVisible = (index: number) => {
  const list = resultListRef.value;
  if (!list) return;
  const itemTop = index * itemHeight.value;
  const itemBottom = itemTop + itemHeight.value;
  const viewTop = list.scrollTop;
  const viewBottom = viewTop + list.clientHeight;

  if (itemTop < viewTop) {
    list.scrollTop = itemTop;
    if (scrollTop.value !== itemTop) {
      scrollTop.value = itemTop;
    }
    return;
  }
  if (itemBottom > viewBottom) {
    const nextTop = Math.max(0, itemBottom - list.clientHeight);
    list.scrollTop = nextTop;
    if (scrollTop.value !== nextTop) {
      scrollTop.value = nextTop;
    }
  }
};

const scrollToSelected = () => {
  nextTick(() => {
    ensureIndexVisible(selectedIndex.value);
  });
};

// 全局快捷键监听
const handleGlobalKeydown = (e: KeyboardEvent) => {
  // Ctrl+K 或 Cmd+K 打开搜索
  if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
    e.preventDefault();
    if (isOpen.value) {
      closeSearch();
    } else {
      openSearch();
    }
  }
};

// 监听关键字变化，重置选中索引
watch(keyword, () => {
  if (selectedIndex.value !== 0) {
    selectedIndex.value = 0;
  }
  if (resultListRef.value) {
    resultListRef.value.scrollTop = 0;
  }
  if (scrollTop.value !== 0) {
    scrollTop.value = 0;
  }
});

watch(isOpen, (open) => {
  if (open) return;
  if (resultListRef.value) {
    resultListRef.value.scrollTop = 0;
  }
  if (scrollTop.value !== 0) {
    scrollTop.value = 0;
  }
});

watch([isOpen, () => searchResults.value.length], ([open]) => {
  if (!open) return;
  nextTick(() => {
    const list = resultListRef.value;
    if (!list) return;
    const firstItem = list.querySelector('.layout-list-item') as HTMLElement | null;
    if (!firstItem) return;
    const height = firstItem.getBoundingClientRect().height;
    if (height > 0 && height !== itemHeight.value) {
      itemHeight.value = height;
    }
    if (typeof ResizeObserver !== 'undefined') {
      listResizeObserver.value?.disconnect();
      listResizeObserver.value = new ResizeObserver(() => {
        const currentItem = list.querySelector('.layout-list-item') as HTMLElement | null;
        if (!currentItem) return;
        const nextHeight = currentItem.getBoundingClientRect().height;
        if (nextHeight > 0 && nextHeight !== itemHeight.value) {
          itemHeight.value = nextHeight;
        }
      });
      listResizeObserver.value.observe(firstItem);
    }
  });
});

watch(isOpen, (open) => {
  if (open) return;
  if (listResizeObserver.value) {
    listResizeObserver.value.disconnect();
    listResizeObserver.value = null;
  }
});

const handleScroll = (e: Event) => {
  const target = e.target as HTMLElement | null;
  if (!target) return;
  const nextTop = target.scrollTop;
  if (scrollTop.value !== nextTop) {
    scrollTop.value = nextTop;
  }
};

const handleWheel = (e: WheelEvent) => {
  if (e.ctrlKey) return;
  e.preventDefault();
  const target = e.currentTarget as HTMLElement | null;
  if (!target) return;
  target.scrollTop += e.deltaY;
  const nextTop = target.scrollTop;
  if (scrollTop.value !== nextTop) {
    scrollTop.value = nextTop;
  }
};

// 监听快捷键
onMounted(() => {
  document.addEventListener('keydown', handleGlobalKeydown);
});

onUnmounted(() => {
  document.removeEventListener('keydown', handleGlobalKeydown);
  if (listResizeObserver.value) {
    listResizeObserver.value.disconnect();
    listResizeObserver.value = null;
  }
});

// 获取快捷键显示文本
const shortcutText = computed(() => {
  const isMac = navigator.platform.toLowerCase().includes('mac');
  return isMac ? '⌘K' : 'Ctrl K';
});
</script>

<template>
  <!-- 搜索按钮 -->
  <button
    type="button"
    class="header-search-btn flex items-center gap-2 rounded-lg border border-gray-200 bg-gray-100/50 px-3 py-1.5 text-sm text-gray-500 transition-colors hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800/50 dark:hover:bg-gray-800"
    :title="context.t('layout.header.search')"
    :data-state="isOpen ? 'open' : 'closed'"
    @click="openSearch"
  >
    <svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
    <span class="hidden md:inline">{{ context.t('layout.header.search') }}</span>
    <kbd class="hidden rounded border border-gray-300 bg-white px-1.5 py-0.5 text-xs font-medium text-gray-500 dark:border-gray-600 dark:bg-gray-700 md:inline">
      {{ shortcutText }}
    </kbd>
  </button>

  <!-- 搜索弹窗 -->
  <Teleport to="body">
    <Transition name="modal">
      <div
        v-if="isOpen"
        class="fixed inset-0 z-9999 flex items-start justify-center px-4 pt-20"
        data-state="open"
      >
        <!-- 遮罩 -->
        <div class="fixed inset-0 bg-black/50" @click="closeSearch" />
        
        <!-- 搜索面板 -->
        <div
          class="relative w-full max-w-xl overflow-hidden rounded-xl bg-white shadow-2xl dark:bg-gray-800"
          @keydown="handleKeydown"
        >
          <!-- 搜索输入框 -->
          <div class="flex items-center border-b px-4 dark:border-gray-700">
            <svg class="h-5 w-5 text-gray-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <circle cx="11" cy="11" r="8" />
              <path d="m21 21-4.3-4.3" />
            </svg>
            <input
              ref="inputRef"
              v-model="keyword"
              type="text"
              class="flex-1 border-0 bg-transparent px-3 py-4 text-base outline-none placeholder:text-gray-400"
              :placeholder="context.t('layout.search.placeholder')"
            />
            <kbd class="rounded border border-gray-300 bg-gray-100 px-1.5 py-0.5 text-xs font-medium text-gray-500 dark:border-gray-600 dark:bg-gray-700">
              ESC
            </kbd>
          </div>
          
          <!-- 搜索结果 -->
          <div
            ref="resultListRef"
            class="layout-scroll-container max-h-80 overflow-y-auto"
            :style="{ height: `${viewportHeight}px`, position: 'relative' }"
            @scroll="handleScroll"
          @wheel="handleWheel"
          >
            <!-- 无结果 -->
            <div v-if="keyword && searchResults.length === 0" class="py-12 text-center text-gray-400">
              {{ context.t('layout.search.noResults') }}
            </div>
            
            <!-- 结果列表 -->
            <template v-else-if="searchResults.length > 0">
              <div :style="{ height: `${totalHeight}px`, pointerEvents: 'none' }" />
              <div
                v-for="(item, index) in visibleResults"
                :key="item.key"
                :data-index="startIndex + index"
                class="layout-list-item flex cursor-pointer items-center gap-3 px-4 py-3 transition-colors"
                :class="startIndex + index === selectedIndex ? 'bg-primary/10 text-primary' : 'hover:bg-gray-100 dark:hover:bg-gray-700/50'"
                :data-selected="startIndex + index === selectedIndex ? 'true' : undefined"
                :style="{
                  position: 'absolute',
                top: `${(startIndex + index) * itemHeight}px`,
                  left: 0,
                  right: 0,
                height: `${itemHeight}px`,
                }"
                @click="handleResultClick"
                @mouseenter="handleResultMouseEnter"
              >
                <!-- 图标 -->
                <div
                  class="flex h-8 w-8 items-center justify-center rounded-lg"
                  :class="startIndex + index === selectedIndex ? 'bg-primary/20' : 'bg-gray-100 dark:bg-gray-700'"
                >
                  <span v-if="item.icon" class="text-lg">{{ item.icon }}</span>
                  <svg v-else class="h-4 w-4 text-gray-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
                    <path d="M9 18c-4.51 2-5-2-7-2" />
                  </svg>
                </div>
                
                <!-- 内容 -->
                <div class="flex-1 overflow-hidden">
                  <div class="truncate font-medium">{{ item.name }}</div>
                  <div v-if="item.parentPath" class="truncate text-xs text-gray-400">
                    {{ item.parentPath.join(' / ') }}
                  </div>
                </div>
                
                <!-- 回车提示 -->
                <span v-if="startIndex + index === selectedIndex" class="text-xs text-gray-400">
                  ↵
                </span>
              </div>
            </template>
            
            <!-- 提示 -->
            <div v-else class="py-8 text-center text-gray-400">
              {{ context.t('layout.search.tips') }}
            </div>
          </div>
          
          <!-- 底部提示 -->
          <div class="flex items-center gap-4 border-t px-4 py-2 text-xs text-gray-400 dark:border-gray-700">
            <span class="flex items-center gap-1">
              <kbd class="rounded border border-gray-300 bg-gray-100 px-1 py-0.5 dark:border-gray-600 dark:bg-gray-700">↑</kbd>
              <kbd class="rounded border border-gray-300 bg-gray-100 px-1 py-0.5 dark:border-gray-600 dark:bg-gray-700">↓</kbd>
              {{ context.t('layout.search.navigate') }}
            </span>
            <span class="flex items-center gap-1">
              <kbd class="rounded border border-gray-300 bg-gray-100 px-1 py-0.5 dark:border-gray-600 dark:bg-gray-700">↵</kbd>
              {{ context.t('layout.search.select') }}
            </span>
            <span class="flex items-center gap-1">
              <kbd class="rounded border border-gray-300 bg-gray-100 px-1 py-0.5 dark:border-gray-600 dark:bg-gray-700">esc</kbd>
              {{ context.t('layout.search.close') }}
            </span>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<style scoped>
.modal-enter-active,
.modal-leave-active {
  transition: opacity 200ms ease;
}

.modal-enter-active > div:last-child,
.modal-leave-active > div:last-child {
  transition: transform 200ms ease, opacity 200ms ease;
}

.modal-enter-from,
.modal-leave-to {
  opacity: 0;
}

.modal-enter-from > div:last-child,
.modal-leave-to > div:last-child {
  transform: scale(0.95);
  opacity: 0;
}
</style>

// packages/layout/react/src/components/widgets/GlobalSearch.tsx
/**
 * 全局搜索组件
 * @description 全局菜单搜索导航，支持快捷键 Ctrl+K
 */
import { useState, useCallback, useMemo, useEffect, useRef, memo } from 'react';
import { createPortal } from 'react-dom';
import { useLayoutContext } from '../../hooks';
import type { MenuItem } from '@admin-core/layout';

interface FlatMenuItem extends MenuItem {
  parentPath?: string[];
  searchText: string;
}

export const GlobalSearch = memo(function GlobalSearch() {
  const { props, events, t } = useLayoutContext();
  const [isOpen, setIsOpen] = useState(false);
  const [keyword, setKeyword] = useState('');
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [scrollTop, setScrollTop] = useState(0);
  const listResizeObserverRef = useRef<ResizeObserver | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const resultListRef = useRef<HTMLDivElement>(null);
  const isOpenRef = useRef(isOpen);

  const menus = props.menus || [];

  // 扁平化菜单
  const flatMenus = useMemo<FlatMenuItem[]>(() => {
    if (!isOpen) return [];
    const result: FlatMenuItem[] = [];

    const flatten = (items: MenuItem[], parentPath: string[] = []) => {
      for (const item of items) {
        const currentPath = [...parentPath, item.name];

        if (item.path && !item.hidden) {
          const name = item.name || '';
          const path = item.path || '';
          result.push({
            ...item,
            parentPath: parentPath.length > 0 ? parentPath : undefined,
            searchText: `${name} ${path}`.toLowerCase(),
          });
        }

        if (item.children?.length) {
          flatten(item.children, currentPath);
        }
      }
    };

    flatten(menus);
    return result;
  }, [menus, isOpen]);

  // 搜索结果
  const MAX_RESULTS = 200;
  const searchResults = useMemo(() => {
    const query = keyword.trim().toLowerCase();
    if (!query) return [];

    const results: FlatMenuItem[] = [];
    for (const item of flatMenus) {
      if (item.searchText.includes(query)) {
        results.push(item);
        if (results.length >= MAX_RESULTS) break;
      }
    }
    return results;
  }, [keyword, flatMenus]);

  const [itemHeight, setItemHeight] = useState(56);
  const RESULT_MAX_HEIGHT = 320;
  const RESULT_OVERSCAN = 4;
  const totalHeight = searchResults.length * itemHeight;
  const viewportHeight = totalHeight === 0 ? RESULT_MAX_HEIGHT : Math.min(totalHeight, RESULT_MAX_HEIGHT);
  const startIndex = Math.max(0, Math.floor(scrollTop / itemHeight) - RESULT_OVERSCAN);
  const endIndex = Math.min(
    searchResults.length,
    Math.ceil((scrollTop + viewportHeight) / itemHeight) + RESULT_OVERSCAN
  );
  const visibleResults = useMemo(
    () => searchResults.slice(startIndex, endIndex),
    [searchResults, startIndex, endIndex]
  );

  // 打开搜索框
  const openSearch = useCallback(() => {
    setIsOpen(true);
    setKeyword('');
    setSelectedIndex(0);
  }, []);

  // 关闭搜索框
  const closeSearch = useCallback(() => {
    setIsOpen(false);
    setKeyword('');
    setSelectedIndex(0);
  }, []);

  const handleKeywordChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    setKeyword(e.target.value);
  }, []);

  // 选择菜单项
  const selectItem = useCallback(
    (item: MenuItem) => {
      if (item.path) {
        events.onGlobalSearch?.(item.path);

        if (props.router?.navigate) {
          props.router.navigate(item.path);
        }
      }
      closeSearch();
    },
    [events, props.router, closeSearch]
  );

  const handleResultClick = useCallback((e: React.MouseEvent) => {
    const index = Number((e.currentTarget as HTMLElement).dataset.index);
    if (!Number.isNaN(index)) {
      const item = searchResults[index];
      if (item) selectItem(item);
    }
  }, [searchResults, selectItem]);

  const handleResultMouseEnter = useCallback((e: React.MouseEvent) => {
    const index = Number((e.currentTarget as HTMLElement).dataset.index);
    if (!Number.isNaN(index)) {
      setSelectedIndex(index);
    }
  }, []);

  // 滚动到选中项
  const ensureIndexVisible = useCallback((index: number) => {
    const list = resultListRef.current;
    if (!list) return;
    const itemTop = index * itemHeight;
    const itemBottom = itemTop + itemHeight;
    const viewTop = list.scrollTop;
    const viewBottom = viewTop + list.clientHeight;

    if (itemTop < viewTop) {
      list.scrollTop = itemTop;
      setScrollTop((prev) => (prev === itemTop ? prev : itemTop));
      return;
    }
    if (itemBottom > viewBottom) {
      const nextTop = Math.max(0, itemBottom - list.clientHeight);
      list.scrollTop = nextTop;
      setScrollTop((prev) => (prev === nextTop ? prev : nextTop));
    }
  }, [itemHeight]);

  const scrollToSelected = useCallback(() => {
    const list = resultListRef.current;
    if (!list) return;
    ensureIndexVisible(selectedIndex);
  }, [ensureIndexVisible, selectedIndex]);

  // 键盘导航
  const handleKeydown = useCallback(
    (e: React.KeyboardEvent) => {
      switch (e.key) {
        case 'ArrowDown':
          e.preventDefault();
          if (selectedIndex < searchResults.length - 1) {
            setSelectedIndex(selectedIndex + 1);
            requestAnimationFrame(scrollToSelected);
          }
          break;
        case 'ArrowUp':
          e.preventDefault();
          if (selectedIndex > 0) {
            setSelectedIndex(selectedIndex - 1);
            requestAnimationFrame(scrollToSelected);
          }
          break;
        case 'Enter':
          e.preventDefault();
          if (searchResults[selectedIndex]) {
            selectItem(searchResults[selectedIndex]);
          }
          break;
        case 'Escape':
          e.preventDefault();
          closeSearch();
          break;
      }
    },
    [selectedIndex, searchResults, selectItem, closeSearch, scrollToSelected]
  );

  const handleScroll = useCallback((e: React.UIEvent<HTMLDivElement>) => {
    const nextTop = e.currentTarget.scrollTop;
    setScrollTop((prev) => (prev === nextTop ? prev : nextTop));
  }, []);

  const handleWheel = useCallback((e: React.WheelEvent<HTMLDivElement>) => {
    if (e.ctrlKey) return;
    e.preventDefault();
    const target = e.currentTarget;
    target.scrollTop += e.deltaY;
    const nextTop = target.scrollTop;
    setScrollTop((prev) => (prev === nextTop ? prev : nextTop));
  }, []);

  // 全局快捷键
  useEffect(() => {
    const handleGlobalKeydown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
        e.preventDefault();
        if (isOpenRef.current) {
          closeSearch();
        } else {
          openSearch();
        }
      }
    };

    document.addEventListener('keydown', handleGlobalKeydown);
    return () => document.removeEventListener('keydown', handleGlobalKeydown);
  }, [openSearch, closeSearch]);

  useEffect(() => {
    isOpenRef.current = isOpen;
  }, [isOpen]);

  useEffect(() => {
    if (!isOpen) return;
    const focusFrame = requestAnimationFrame(() => {
      inputRef.current?.focus();
    });
    return () => cancelAnimationFrame(focusFrame);
  }, [isOpen]);

  useEffect(() => {
    if (!isOpen) return;
    const list = resultListRef.current;
    if (!list) return;
    const updateItemHeight = () => {
      const firstItem = list.querySelector('.layout-list-item') as HTMLElement | null;
      if (!firstItem) return;
      const height = firstItem.getBoundingClientRect().height;
      if (height > 0 && height !== itemHeight) {
        setItemHeight(height);
      }
    };
    const frame = requestAnimationFrame(updateItemHeight);
    if (typeof ResizeObserver !== 'undefined') {
      const firstItem = list.querySelector('.layout-list-item') as HTMLElement | null;
      if (firstItem) {
        const observer = new ResizeObserver(updateItemHeight);
        observer.observe(firstItem);
        listResizeObserverRef.current = observer;
      }
    }
    return () => {
      cancelAnimationFrame(frame);
      if (listResizeObserverRef.current) {
        listResizeObserverRef.current.disconnect();
        listResizeObserverRef.current = null;
      }
    };
  }, [isOpen, searchResults.length, itemHeight]);

  // 重置选中索引
  useEffect(() => {
    setSelectedIndex((prev) => (prev === 0 ? prev : 0));
    if (resultListRef.current) {
      resultListRef.current.scrollTop = 0;
    }
    setScrollTop((prev) => (prev === 0 ? prev : 0));
  }, [keyword]);

  useEffect(() => {
    if (isOpen) return;
    if (resultListRef.current) {
      resultListRef.current.scrollTop = 0;
    }
    setScrollTop((prev) => (prev === 0 ? prev : 0));
  }, [isOpen]);

  useEffect(() => {
    if (!isOpen) return;
    const maxScrollTop = Math.max(0, totalHeight - viewportHeight);
    if (scrollTop <= maxScrollTop) return;
    const nextTop = Math.max(0, maxScrollTop);
    if (resultListRef.current) {
      resultListRef.current.scrollTop = nextTop;
    }
    setScrollTop((prev) => (prev === nextTop ? prev : nextTop));
  }, [isOpen, totalHeight, viewportHeight, scrollTop]);

  const shortcutText = useMemo(() => {
    const isMac = navigator.platform.toLowerCase().includes('mac');
    return isMac ? '⌘K' : 'Ctrl K';
  }, []);

  return (
    <>
      <button
        type="button"
        className="header-search-btn flex items-center gap-2 rounded-lg border border-gray-200 bg-gray-100/50 px-3 py-1.5 text-sm text-gray-500 transition-colors hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800/50 dark:hover:bg-gray-800"
        title={t('layout.header.search')}
        data-state={isOpen ? 'open' : 'closed'}
        onClick={openSearch}
      >
        <svg
          className="h-4 w-4"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth={2}
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <circle cx="11" cy="11" r="8" />
          <path d="m21 21-4.3-4.3" />
        </svg>
        <span className="hidden md:inline">{t('layout.header.search')}</span>
        <kbd className="hidden rounded border border-gray-300 bg-white px-1.5 py-0.5 text-xs font-medium text-gray-500 dark:border-gray-600 dark:bg-gray-700 md:inline">
          {shortcutText}
        </kbd>
      </button>

      {isOpen &&
        createPortal(
          <div className="fixed inset-0 z-9999 flex items-start justify-center px-4 pt-20" data-state="open">
            <div className="fixed inset-0 bg-black/50" onClick={closeSearch} />

            <div
              className="relative w-full max-w-xl overflow-hidden rounded-xl bg-white shadow-2xl dark:bg-gray-800"
              onKeyDown={handleKeydown}
            >
              <div className="flex items-center border-b px-4 dark:border-gray-700">
                <svg
                  className="h-5 w-5 text-gray-400"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth={2}
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <circle cx="11" cy="11" r="8" />
                  <path d="m21 21-4.3-4.3" />
                </svg>
                <input
                  ref={inputRef}
                  type="text"
                  value={keyword}
                  onChange={handleKeywordChange}
                  className="flex-1 border-0 bg-transparent px-3 py-4 text-base outline-none placeholder:text-gray-400"
                  placeholder={t('layout.search.placeholder')}
                />
                <kbd className="rounded border border-gray-300 bg-gray-100 px-1.5 py-0.5 text-xs font-medium text-gray-500 dark:border-gray-600 dark:bg-gray-700">
                  ESC
                </kbd>
              </div>

              <div
                ref={resultListRef}
                className="layout-scroll-container max-h-80 overflow-y-auto"
                style={{ height: `${viewportHeight}px`, position: 'relative' }}
                onScroll={handleScroll}
                onWheel={handleWheel}
              >
                {keyword && searchResults.length === 0 ? (
                  <div className="py-12 text-center text-gray-400">{t('layout.search.noResults')}</div>
                ) : searchResults.length > 0 ? (
                  <>
                    <div style={{ height: `${totalHeight}px`, pointerEvents: 'none' }} />
                    {visibleResults.map((item, index) => {
                      const actualIndex = startIndex + index;
                      return (
                        <div
                          key={item.key}
                          data-index={actualIndex}
                          className={`layout-list-item flex cursor-pointer items-center gap-3 px-4 py-3 transition-colors ${
                            actualIndex === selectedIndex
                              ? 'bg-primary/10 text-primary'
                              : 'hover:bg-gray-100 dark:hover:bg-gray-700/50'
                          }`}
                          data-selected={actualIndex === selectedIndex ? 'true' : undefined}
                          onClick={handleResultClick}
                          onMouseEnter={handleResultMouseEnter}
                          style={{
                            position: 'absolute',
                            top: `${actualIndex * itemHeight}px`,
                            left: 0,
                            right: 0,
                            height: `${itemHeight}px`,
                          }}
                        >
                          <div
                            className={`flex h-8 w-8 items-center justify-center rounded-lg ${
                              actualIndex === selectedIndex ? 'bg-primary/20' : 'bg-gray-100 dark:bg-gray-700'
                            }`}
                          >
                            {item.icon ? (
                              <span className="text-lg">{item.icon}</span>
                            ) : (
                              <svg className="h-4 w-4 text-gray-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
                                <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
                                <path d="M9 18c-4.51 2-5-2-7-2" />
                              </svg>
                            )}
                          </div>
                          <div className="flex-1 overflow-hidden">
                            <div className="truncate font-medium">{item.name}</div>
                            {item.parentPath && (
                              <div className="truncate text-xs text-gray-400">{item.parentPath.join(' / ')}</div>
                            )}
                          </div>
                          {actualIndex === selectedIndex && <span className="text-xs text-gray-400">↵</span>}
                        </div>
                      );
                    })}
                  </>
                ) : (
                  <div className="py-8 text-center text-gray-400">{t('layout.search.tips')}</div>
                )}
              </div>

              <div className="flex items-center gap-4 border-t px-4 py-2 text-xs text-gray-400 dark:border-gray-700">
                <span className="flex items-center gap-1">
                  <kbd className="rounded border border-gray-300 bg-gray-100 px-1 py-0.5 dark:border-gray-600 dark:bg-gray-700">↑</kbd>
                  <kbd className="rounded border border-gray-300 bg-gray-100 px-1 py-0.5 dark:border-gray-600 dark:bg-gray-700">↓</kbd>
                  {t('layout.search.navigate')}
                </span>
                <span className="flex items-center gap-1">
                  <kbd className="rounded border border-gray-300 bg-gray-100 px-1 py-0.5 dark:border-gray-600 dark:bg-gray-700">↵</kbd>
                  {t('layout.search.select')}
                </span>
                <span className="flex items-center gap-1">
                  <kbd className="rounded border border-gray-300 bg-gray-100 px-1 py-0.5 dark:border-gray-600 dark:bg-gray-700">esc</kbd>
                  {t('layout.search.close')}
                </span>
              </div>
            </div>
          </div>,
          document.body
        )}
    </>
  );
});
