// packages/layout/react/src/components/layout/LayoutTabbar.tsx
/**
 * 标签栏组件
 * @description 支持拖拽排序、中键关闭、滚轮滚动、最大化、右键菜单等功能
 */

import { useState, useRef, useEffect, useLayoutEffect, useCallback, useMemo, memo, type ReactNode, type CSSProperties } from 'react';
import { createPortal } from 'react-dom';
import { renderLayoutIcon } from '../../utils';
import { useLayoutContext, useLayoutComputed } from '../../hooks';
import { useTabsState, useSidebarState } from '../../hooks/use-layout-state';
import {
  generateContextMenuItems,
  type ContextMenuAction,
  type TabItem,
} from '@admin-core/layout';

export interface LayoutTabbarProps {
  left?: ReactNode;
  tabs?: ReactNode;
  right?: ReactNode;
  extra?: ReactNode;
}

export const LayoutTabbar = memo(function LayoutTabbar({
  left,
  tabs: tabsSlot,
  right,
  extra,
}: LayoutTabbarProps) {
  const context = useLayoutContext();
  const computed = useLayoutComputed();
  const {
    tabs,
    activeKey,
    handleSelect,
    handleClose,
    handleCloseAll,
    handleCloseOther,
    handleCloseLeft,
    handleCloseRight,
    handleRefresh,
    handleToggleAffix,
    handleOpenInNewWindow,
    handleSort,
  } = useTabsState();
  const { collapsed: sidebarCollapsed } = useSidebarState();

  const tabbarConfig = context.props.tabbar || {};
  const styleType = tabbarConfig.styleType || 'chrome';
  const headerMode = context.props.header?.mode || 'fixed';
  const isHeaderFixed = headerMode !== 'static';
  const leftOffset = computed.mainStyle.marginLeft || '0';
  const panelRightOffset = computed.mainStyle.marginRight || '0';

  // 标签列表容器引用
  const tabsContainerRef = useRef<HTMLDivElement>(null);
  const tabRefs = useRef(new Map<string, HTMLDivElement>());
  const flipStateRef = useRef<{ pending: boolean; positions: Map<string, DOMRect> }>({
    pending: false,
    positions: new Map(),
  });

  const recordTabPositions = useCallback(() => {
    const map = new Map<string, DOMRect>();
    tabRefs.current.forEach((el, key) => {
      map.set(key, el.getBoundingClientRect());
    });
    flipStateRef.current.positions = map;
    flipStateRef.current.pending = true;
  }, []);

  const animateTabPositions = useCallback(() => {
    if (!flipStateRef.current.pending) return;
    const prevPositions = flipStateRef.current.positions;
    flipStateRef.current.pending = false;
    const animated: HTMLDivElement[] = [];
    tabRefs.current.forEach((el, key) => {
      const prevRect = prevPositions.get(key);
      if (!prevRect) return;
      const nextRect = el.getBoundingClientRect();
      const dx = prevRect.left - nextRect.left;
      const dy = prevRect.top - nextRect.top;
      if (dx || dy) {
        el.style.transition = 'transform 0s';
        el.style.transform = `translate(${dx}px, ${dy}px)`;
        animated.push(el);
      }
    });
    if (!animated.length) return;
    requestAnimationFrame(() => {
      animated.forEach((el) => {
        el.style.transition = 'transform 300ms var(--admin-easing-default, cubic-bezier(0.4, 0, 0.2, 1))';
        el.style.transform = '';
      });
      window.setTimeout(() => {
        animated.forEach((el) => {
          el.style.transition = '';
        });
      }, 320);
    });
  }, []);

  // 拖拽状态
  const [dragState, setDragState] = useState<{
    isDragging: boolean;
    dragIndex: number | null;
    dropIndex: number | null;
  }>({
    isDragging: false,
    dragIndex: null,
    dropIndex: null,
  });

  // 最大化状态
  const [isMaximized, setIsMaximized] = useState(false);

  // 右键菜单状态
  const [contextMenu, setContextMenu] = useState<{
    visible: boolean;
    x: number;
    y: number;
    targetKey: string | null;
  }>({
    visible: false,
    x: 0,
    y: 0,
    targetKey: null,
  });

  // 更多菜单状态
  const [moreMenu, setMoreMenu] = useState<{
    visible: boolean;
    x: number;
    y: number;
  }>({
    visible: false,
    x: 0,
    y: 0,
  });
  const moreMenuAnchorRef = useRef<HTMLButtonElement>(null);
  const contextMenuRef = useRef<HTMLDivElement>(null);
  const moreMenuRef = useRef<HTMLDivElement>(null);

  const tabMap = useMemo(() => {
    const map = new Map<string, TabItem>();
    for (const tab of tabs) {
      map.set(tab.key, tab);
    }
    return map;
  }, [tabs]);
  const tabIndexMap = useMemo(() => {
    const map = new Map<string, number>();
    tabs.forEach((tab, index) => map.set(tab.key, index));
    return map;
  }, [tabs]);

  const TAB_RENDER_CHUNK = 60;
  const [tabRenderCount, setTabRenderCount] = useState(TAB_RENDER_CHUNK);

  // 类名
  const tabbarClassName = useMemo(() => {
    const classes = ['layout-tabbar', `layout-tabbar--${styleType}`];
    if (computed.showSidebar && !context.props.isMobile) {
      classes.push('layout-tabbar--with-sidebar');
    }
    if (sidebarCollapsed && !context.props.isMobile) {
      classes.push('layout-tabbar--collapsed');
    }
    return classes.join(' ');
  }, [styleType, computed.showSidebar, context.props.isMobile, sidebarCollapsed]);

  // 样式
  const tabbarStyle = useMemo(() => {
    const style: CSSProperties = {
      height: `${computed.tabbarHeight}px`,
    };

    if (isHeaderFixed) {
      style.position = 'fixed';
      style.top = `${computed.headerHeight}px`;
      style.left = leftOffset;
      if (panelRightOffset !== '0') {
        style.right = panelRightOffset;
      }
    } else {
      style.position = 'static';
      if (leftOffset !== '0') {
        style.marginLeft = leftOffset;
      }
      if (panelRightOffset !== '0') {
        style.marginRight = panelRightOffset;
      }
      if (leftOffset !== '0' || panelRightOffset !== '0') {
        const leftValue = leftOffset !== '0' ? leftOffset : '0px';
        const rightValue = panelRightOffset !== '0' ? panelRightOffset : '0px';
        style.width = `calc(100% - ${leftValue} - ${rightValue})`;
      }
    }

    return style;
  }, [computed.tabbarHeight, computed.headerHeight, isHeaderFixed, leftOffset, panelRightOffset]);

  // 渲染数量
  useEffect(() => {
    const activeIndex = tabIndexMap.get(activeKey ?? '') ?? -1;
    if (activeIndex >= 0) {
      setTabRenderCount(Math.min(tabs.length, Math.max(TAB_RENDER_CHUNK, activeIndex + 1)));
    } else {
      setTabRenderCount(Math.min(TAB_RENDER_CHUNK, tabs.length));
    }
  }, [tabs, activeKey, tabIndexMap]);

  useEffect(() => {
    if (tabRenderCount >= tabs.length) return;
    const frame = requestAnimationFrame(() => {
      setTabRenderCount((prev) => Math.min(prev + TAB_RENDER_CHUNK, tabs.length));
    });
    return () => cancelAnimationFrame(frame);
  }, [tabRenderCount, tabs.length]);

  const visibleTabs = useMemo(() => tabs.slice(0, tabRenderCount), [tabs, tabRenderCount]);

  // 滚动状态
  const [canScrollLeft, setCanScrollLeft] = useState(false);
  const [canScrollRight, setCanScrollRight] = useState(false);

  const updateScrollState = useCallback(() => {
    const container = tabsContainerRef.current;
    if (!container) {
      setCanScrollLeft(false);
      setCanScrollRight(false);
      return;
    }
    const { scrollLeft, scrollWidth, clientWidth } = container;
    setCanScrollLeft(scrollLeft > 0);
    setCanScrollRight(scrollLeft + clientWidth < scrollWidth - 1);
  }, []);

  useEffect(() => {
    updateScrollState();
  }, [tabs, tabRenderCount, updateScrollState]);

  useEffect(() => {
    window.addEventListener('resize', updateScrollState);
    return () => window.removeEventListener('resize', updateScrollState);
  }, [updateScrollState]);

  useEffect(() => {
    const key = activeKey ?? '';
    const el = tabRefs.current.get(key);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', inline: 'center', block: 'nearest' });
    }
  }, [activeKey, visibleTabs]);

  useLayoutEffect(() => {
    animateTabPositions();
  }, [tabs, animateTabPositions]);

  const scrollTabsBy = useCallback((direction: number) => {
    const container = tabsContainerRef.current;
    if (!container) return;
    const offset = Math.max(container.clientWidth * 0.6, 120);
    container.scrollBy({ left: offset * direction, behavior: 'smooth' });
    requestAnimationFrame(updateScrollState);
  }, [updateScrollState]);

  const closeContextMenu = useCallback(() => {
    setContextMenu((prev) => ({ ...prev, visible: false, targetKey: null }));
  }, []);

  const closeMoreMenu = useCallback(() => {
    setMoreMenu((prev) => ({ ...prev, visible: false }));
  }, []);

  const openMoreMenu = useCallback(() => {
    if (!moreMenuAnchorRef.current) return;
    const rect = moreMenuAnchorRef.current.getBoundingClientRect();
    setMoreMenu({
      visible: !moreMenu.visible,
      x: rect.left,
      y: rect.bottom + 6,
    });
    setContextMenu((prev) => ({ ...prev, visible: false, targetKey: null }));
  }, [moreMenu.visible]);

  const adjustMenuPosition = useCallback((menu: { x: number; y: number }, el: HTMLDivElement | null) => {
    if (!el || typeof window === 'undefined') return menu;
    const margin = 8;
    const rect = el.getBoundingClientRect();
    let x = menu.x;
    let y = menu.y;
    const maxX = window.innerWidth - rect.width - margin;
    const maxY = window.innerHeight - rect.height - margin;
    if (rect.left < margin) x = margin;
    if (rect.right > window.innerWidth - margin) x = Math.max(margin, maxX);
    if (rect.top < margin) y = margin;
    if (rect.bottom > window.innerHeight - margin) y = Math.max(margin, maxY);
    return x === menu.x && y === menu.y ? menu : { x, y };
  }, []);

  useLayoutEffect(() => {
    if (!contextMenu.visible) return;
    const next = adjustMenuPosition({ x: contextMenu.x, y: contextMenu.y }, contextMenuRef.current);
    if (next.x !== contextMenu.x || next.y !== contextMenu.y) {
      setContextMenu((prev) => ({ ...prev, x: next.x, y: next.y }));
    }
  }, [contextMenu.visible, contextMenu.x, contextMenu.y, adjustMenuPosition]);

  useLayoutEffect(() => {
    if (!moreMenu.visible) return;
    const next = adjustMenuPosition({ x: moreMenu.x, y: moreMenu.y }, moreMenuRef.current);
    if (next.x !== moreMenu.x || next.y !== moreMenu.y) {
      setMoreMenu((prev) => ({ ...prev, x: next.x, y: next.y }));
    }
  }, [moreMenu.visible, moreMenu.x, moreMenu.y, adjustMenuPosition]);

  const toggleMaximize = useCallback(() => {
    setIsMaximized((prev) => {
      const next = !prev;
      context.events?.onTabMaximize?.(next);
      if (next) {
        document.body.classList.add('layout-content-maximized');
        document.body.dataset.contentMaximized = 'true';
      } else {
        document.body.classList.remove('layout-content-maximized');
        delete document.body.dataset.contentMaximized;
      }
      return next;
    });
  }, [context.events]);

  const handleMenuAction = useCallback((action: ContextMenuAction, targetKey: string | null) => {
    if (!targetKey) return;
    switch (action) {
      case 'refresh':
        handleRefresh(targetKey);
        break;
      case 'close':
        handleClose(targetKey);
        break;
      case 'closeOther':
        handleCloseOther(targetKey);
        break;
      case 'closeLeft':
        handleCloseLeft(targetKey);
        break;
      case 'closeRight':
        handleCloseRight(targetKey);
        break;
      case 'closeAll':
        handleCloseAll();
        break;
      case 'pin':
      case 'unpin':
        handleToggleAffix(targetKey);
        break;
      case 'openInNewWindow':
        handleOpenInNewWindow(targetKey);
        break;
      case 'maximize':
        if (!isMaximized) {
          if (targetKey !== activeKey) {
            handleSelect(targetKey);
          }
          toggleMaximize();
        }
        break;
      case 'restoreMaximize':
        if (isMaximized) {
          toggleMaximize();
        }
        break;
      default:
        break;
    }
  }, [
    handleRefresh,
    handleClose,
    handleCloseOther,
    handleCloseLeft,
    handleCloseRight,
    handleCloseAll,
    handleToggleAffix,
    handleOpenInNewWindow,
    handleSelect,
    activeKey,
    isMaximized,
    toggleMaximize,
  ]);

  const contextMenuItems = useMemo(() => {
    if (!contextMenu.targetKey) return [];
    const tab = tabMap.get(contextMenu.targetKey);
    if (!tab) return [];
    const items = generateContextMenuItems(
      tab,
      tabs,
      activeKey ?? '',
      context.t,
      tabIndexMap,
      { isMaximized }
    );
    return items.filter((item) => {
      if (item.key === 'maximize' || item.key === 'restoreMaximize') {
        return tabbarConfig.showMaximize !== false;
      }
      return true;
    });
  }, [contextMenu.targetKey, tabMap, tabs, activeKey, tabIndexMap, context.t, isMaximized, tabbarConfig.showMaximize]);

  const moreMenuItems = useMemo(() => {
    const key = activeKey ?? tabs[0]?.key ?? '';
    if (!key) return [];
    const tab = tabMap.get(key);
    if (!tab) return [];
    const items = generateContextMenuItems(
      tab,
      tabs,
      activeKey ?? '',
      context.t,
      tabIndexMap,
      { isMaximized }
    );
    return items.filter((item) => {
      if (item.key === 'maximize' || item.key === 'restoreMaximize') {
        return tabbarConfig.showMaximize !== false;
      }
      return true;
    });
  }, [activeKey, tabs, tabMap, tabIndexMap, context.t, isMaximized, tabbarConfig.showMaximize]);

  const onContextMenu = useCallback((e: React.MouseEvent, key: string) => {
    e.preventDefault();
    setContextMenu({
      visible: true,
      x: e.clientX,
      y: e.clientY,
      targetKey: key,
    });
    setMoreMenu((prev) => ({ ...prev, visible: false }));
  }, []);

  const handleTabClick = useCallback((e: React.MouseEvent) => {
    const key = (e.currentTarget as HTMLElement).dataset.key;
    if (key) {
      handleSelect(key);
    }
  }, [handleSelect]);

  const handleTabContextMenu = useCallback((e: React.MouseEvent) => {
    const key = (e.currentTarget as HTMLElement).dataset.key;
    if (key) {
      onContextMenu(e, key);
    }
  }, [onContextMenu]);

  const handleTabCloseClick = useCallback((e: React.MouseEvent) => {
    e.stopPropagation();
    const key = (e.currentTarget as HTMLElement).dataset.key;
    if (key) {
      handleClose(key);
    }
  }, [handleClose]);

  const handleMouseDown = useCallback((e: React.MouseEvent, tab: TabItem) => {
    if (e.button === 1 && tabbarConfig.middleClickToClose !== false) {
      e.preventDefault();
      if (tab.closable !== false && !tab.affix) {
        handleClose(tab.key);
      }
    }
  }, [tabbarConfig.middleClickToClose, handleClose]);

  const handleWheel = useCallback((e: React.WheelEvent) => {
    if (!tabbarConfig.wheelable) return;
    const container = tabsContainerRef.current;
    if (!container) return;
    if (container.scrollWidth <= container.clientWidth) return;
    e.preventDefault();
    const delta = Math.abs(e.deltaY) > Math.abs(e.deltaX) ? e.deltaY : e.deltaX;
    container.scrollLeft += delta;
    updateScrollState();
  }, [tabbarConfig.wheelable, updateScrollState]);

  const onDragStart = useCallback((e: React.DragEvent, index: number) => {
    if (!tabbarConfig.draggable) return;
    const tab = tabs[index];
    if (tab?.affix) {
      e.preventDefault();
      return;
    }
    setDragState({
      isDragging: true,
      dragIndex: index,
      dropIndex: null,
    });
    e.dataTransfer.effectAllowed = 'move';
    e.dataTransfer.setData('text/plain', String(index));
  }, [tabbarConfig.draggable, tabs]);

  const onDragOver = useCallback((e: React.DragEvent, index: number) => {
    if (!tabbarConfig.draggable || !dragState.isDragging) return;
    e.preventDefault();
    const tab = tabs[index];
    if (tab?.affix) return;
    const fromIndex = dragState.dragIndex;
    if (fromIndex === null) return;
    setDragState((prev) => ({ ...prev, dropIndex: index }));
    if (fromIndex === index) return;
    const targetKey = tab.key;
    const targetEl = tabRefs.current.get(targetKey);
    if (!targetEl) return;
    const rect = targetEl.getBoundingClientRect();
    const midpoint = rect.left + rect.width / 2;
    const shouldMove =
      (fromIndex < index && e.clientX > midpoint) ||
      (fromIndex > index && e.clientX < midpoint);
    if (!shouldMove) return;
    recordTabPositions();
    handleSort(fromIndex, index);
    setDragState((prev) => ({ ...prev, dragIndex: index, dropIndex: index }));
  }, [tabbarConfig.draggable, dragState.isDragging, dragState.dragIndex, tabs, handleSort, recordTabPositions]);

  const onDrop = useCallback((e: React.DragEvent, toIndex: number) => {
    if (!tabbarConfig.draggable) return;
    e.preventDefault();
    const fromIndex = dragState.dragIndex;
    if (fromIndex !== null && fromIndex !== toIndex) {
      const targetTab = tabs[toIndex];
      if (!targetTab?.affix) {
        recordTabPositions();
        handleSort(fromIndex, toIndex);
      }
    }
    setDragState({ isDragging: false, dragIndex: null, dropIndex: null });
  }, [tabbarConfig.draggable, dragState.dragIndex, tabs, handleSort, recordTabPositions]);

  const onDragEnd = useCallback(() => {
    setDragState({ isDragging: false, dragIndex: null, dropIndex: null });
  }, []);

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        setIsMaximized(false);
        context.events?.onTabMaximize?.(false);
        document.body.classList.remove('layout-content-maximized');
        delete document.body.dataset.contentMaximized;
      }
    };
    if (isMaximized) {
      document.addEventListener('keydown', handler);
    }
    return () => {
      document.removeEventListener('keydown', handler);
    };
  }, [isMaximized, context.events]);

  const getTabTitle = useCallback((tab: TabItem) => {
    const meta = tab.meta as Record<string, unknown> | undefined;
    const title = (meta?.newTabTitle as string | undefined) || (meta?.title as string | undefined) || tab.name;
    return context.t(title);
  }, [context.t]);

  const isChrome = styleType === 'chrome';

  const showScrollButtons = canScrollLeft || canScrollRight;

  return (
    <div
      className={tabbarClassName}
      style={tabbarStyle}
      data-with-sidebar={computed.showSidebar && !context.props.isMobile ? 'true' : undefined}
      data-collapsed={sidebarCollapsed && !context.props.isMobile ? 'true' : undefined}
      data-style={styleType}
      onClick={() => { closeContextMenu(); closeMoreMenu(); }}
    >
      <div className="layout-tabbar__inner flex h-full">
        {left ? <div className="layout-tabbar__left shrink-0 px-2">{left}</div> : null}

        {showScrollButtons ? (
          <button
            type="button"
            className="layout-tabbar__scroll-btn layout-tabbar__scroll-btn--left"
            data-disabled={canScrollLeft ? 'false' : 'true'}
            disabled={!canScrollLeft}
            onClick={(e) => {
              e.stopPropagation();
              if (canScrollLeft) scrollTabsBy(-1);
            }}
          >
            {renderLayoutIcon('tabbar-scroll-left', 'sm')}
          </button>
        ) : null}

        <div
          ref={tabsContainerRef}
          className="layout-tabbar__tabs layout-scroll-container flex h-full flex-1 overflow-x-auto scrollbar-none"
          data-dragging={dragState.isDragging ? 'true' : undefined}
          onWheel={handleWheel}
          onScroll={updateScrollState}
        >
          {tabsSlot || (
            visibleTabs.map((tab, index) => {
              const showIcon = tabbarConfig.showIcon && tab.icon;
              const showPin = !!tab.affix;
              const showClose = tab.closable !== false && !tab.affix;
              return (
                <div
                  key={tab.key}
                  ref={(el) => {
                    if (el) {
                      tabRefs.current.set(tab.key, el);
                    } else {
                      tabRefs.current.delete(tab.key);
                    }
                  }}
                  data-key={tab.key}
                  data-index={index}
                  data-state={tab.key === activeKey ? 'active' : 'inactive'}
                  data-style={styleType}
                  data-hovered={undefined}
                  data-affix={tab.affix ? 'true' : undefined}
                  data-dragging={dragState.isDragging && dragState.dragIndex === index ? 'true' : undefined}
                  data-drop-target={dragState.isDragging && dragState.dropIndex === index ? 'true' : undefined}
                  className={[
                    'layout-tabbar__tab',
                    `layout-tabbar__tab--${styleType}`,
                    'group',
                    tab.key === activeKey ? 'layout-tabbar__tab--active' : '',
                    tab.affix ? 'layout-tabbar__tab--affix' : '',
                    dragState.isDragging && dragState.dragIndex === index ? 'layout-tabbar__tab--dragging' : '',
                    dragState.isDragging && dragState.dropIndex === index ? 'layout-tabbar__tab--drop-target' : '',
                  ].filter(Boolean).join(' ')}
                  draggable={tabbarConfig.draggable && !tab.affix}
                  onClick={handleTabClick}
                  onContextMenu={handleTabContextMenu}
                  onMouseDown={(e) => handleMouseDown(e, tab)}
                  onDragStart={(e) => onDragStart(e, index)}
                  onDragOver={(e) => onDragOver(e, index)}
                  onDragLeave={() => setDragState((prev) => ({ ...prev, dropIndex: null }))}
                  onDrop={(e) => onDrop(e, index)}
                  onDragEnd={onDragEnd}
                >
                  {isChrome ? (
                    <div className="layout-tabbar__chrome">
                      <div className="layout-tabbar__chrome-divider" />
                      <div className="layout-tabbar__chrome-bg">
                        <div className="layout-tabbar__chrome-bg-content" />
                        <svg className="layout-tabbar__chrome-bg-before" height="7" width="7" viewBox="0 0 7 7">
                          <path d="M 0 7 A 7 7 0 0 0 7 0 L 7 7 Z" />
                        </svg>
                        <svg className="layout-tabbar__chrome-bg-after" height="7" width="7" viewBox="0 0 7 7">
                          <path d="M 0 0 A 7 7 0 0 0 7 7 L 0 7 Z" />
                        </svg>
                      </div>
                      <div className="layout-tabbar__chrome-main">
                        {showIcon ? (
                          <span className="layout-tabbar__tab-icon">
                            <span className="text-sm">{tab.icon}</span>
                          </span>
                        ) : null}
                        <span className="layout-tabbar__tab-name truncate">{getTabTitle(tab)}</span>
                      </div>
                      <div className="layout-tabbar__chrome-extra">
                        {showPin ? (
                          <button
                            type="button"
                            className="layout-tabbar__tab-pin"
                            onClick={(e) => { e.stopPropagation(); handleToggleAffix(tab.key); }}
                          >
                            {renderLayoutIcon('tabbar-pin', 'xs')}
                          </button>
                        ) : null}
                        {showClose ? (
                          <button
                            type="button"
                            data-key={tab.key}
                            className="layout-tabbar__tab-close"
                            onClick={handleTabCloseClick}
                          >
                            {renderLayoutIcon('tabbar-close', 'xs')}
                          </button>
                        ) : null}
                      </div>
                    </div>
                  ) : (
                    <div className="layout-tabbar__tab-content">
                      <div className="layout-tabbar__tab-extra">
                        {showClose ? (
                          <button
                            type="button"
                            data-key={tab.key}
                            className="layout-tabbar__tab-close"
                            onClick={handleTabCloseClick}
                          >
                            {renderLayoutIcon('tabbar-close', 'xs')}
                          </button>
                        ) : null}
                        {showPin ? (
                          <button
                            type="button"
                            className="layout-tabbar__tab-pin"
                            onClick={(e) => { e.stopPropagation(); handleToggleAffix(tab.key); }}
                          >
                            {renderLayoutIcon('tabbar-pin', 'xs')}
                          </button>
                        ) : null}
                      </div>
                      <div className="layout-tabbar__tab-main">
                        {showIcon ? (
                          <span className="layout-tabbar__tab-icon">
                            <span className="text-sm">{tab.icon}</span>
                          </span>
                        ) : null}
                        <span className="layout-tabbar__tab-name truncate">{getTabTitle(tab)}</span>
                      </div>
                    </div>
                  )}
                </div>
              );
            })
          )}
        </div>

        {showScrollButtons ? (
          <button
            type="button"
            className="layout-tabbar__scroll-btn layout-tabbar__scroll-btn--right"
            data-disabled={canScrollRight ? 'false' : 'true'}
            disabled={!canScrollRight}
            onClick={(e) => {
              e.stopPropagation();
              if (canScrollRight) scrollTabsBy(1);
            }}
          >
            {renderLayoutIcon('tabbar-scroll-right', 'sm')}
          </button>
        ) : null}

        {right ? <div className="layout-tabbar__right shrink-0 px-2">{right}</div> : null}

        {tabbarConfig.showMaximize ? (
          <button
            type="button"
            className="layout-tabbar__tool-btn"
            title={isMaximized ? context.t('layout.tabbar.restore') : context.t('layout.tabbar.maximize')}
            onClick={(e) => { e.stopPropagation(); toggleMaximize(); }}
          >
            {!isMaximized ? renderLayoutIcon('tabbar-maximize', 'sm') : renderLayoutIcon('tabbar-restore', 'sm')}
          </button>
        ) : null}

        {tabbarConfig.showMore !== false ? (
          <div className="layout-tabbar__more">
            {extra || (
              <button
                ref={moreMenuAnchorRef}
                type="button"
                className="layout-tabbar__tool-btn"
                title={context.t('layout.common.more')}
                onClick={(e) => { e.stopPropagation(); openMoreMenu(); }}
              >
                {renderLayoutIcon('tabbar-more', 'sm')}
              </button>
            )}
          </div>
        ) : null}
      </div>

      {contextMenu.visible && createPortal(
        <>
          <div
            ref={contextMenuRef}
            className="layout-tabbar__context-menu fixed z-layout-overlay min-w-40 rounded-md border border-border py-1 shadow-lg"
            style={{ left: `${contextMenu.x}px`, top: `${contextMenu.y}px` }}
          >
            {contextMenuItems.map((item) => (
              item.divider ? (
                <div key={item.key} className="my-1 h-px bg-border" />
              ) : (
                <button
                  key={item.key}
                  type="button"
                  className="layout-tabbar__menu-item flex w-full items-center px-3 py-1.5 text-sm disabled:cursor-not-allowed disabled:opacity-50"
                  disabled={item.disabled}
                  onClick={() => { handleMenuAction(item.key, contextMenu.targetKey); closeContextMenu(); }}
                >
                  {item.label}
                </button>
              )
            ))}
          </div>
          <div className="fixed inset-0 z-layout-overlay" onClick={closeContextMenu} />
        </>,
        document.body
      )}

      {moreMenu.visible && createPortal(
        <>
          <div
            ref={moreMenuRef}
            className="layout-tabbar__more-menu fixed z-layout-overlay min-w-40 rounded-md border border-border py-1 shadow-lg"
            style={{ left: `${moreMenu.x}px`, top: `${moreMenu.y}px` }}
          >
            {moreMenuItems.map((item) => (
              item.divider ? (
                <div key={item.key} className="my-1 h-px bg-border" />
              ) : (
                <button
                  key={item.key}
                  type="button"
                  className="layout-tabbar__menu-item flex w-full items-center px-3 py-1.5 text-sm disabled:cursor-not-allowed disabled:opacity-50"
                  disabled={item.disabled}
                  onClick={() => { handleMenuAction(item.key, activeKey ?? tabs[0]?.key ?? null); closeMoreMenu(); }}
                >
                  {item.label}
                </button>
              )
            ))}
          </div>
          <div className="fixed inset-0 z-layout-overlay" onClick={closeMoreMenu} />
        </>,
        document.body
      )}
    </div>
  );
});

// packages/layout/vue/src/components/layout/LayoutTabbar.vue
<script setup lang="ts">
/**
 * 标签栏组件
 * @description 支持拖拽排序、中键关闭、滚轮滚动、最大化、右键菜单等功能
 */
import { computed, nextTick, onMounted, onUnmounted, ref, watch, watchEffect, type ComponentPublicInstance } from 'vue';
import { useLayoutContext, useLayoutComputed, useTabsState, useSidebarState } from '../../composables';
import LayoutIcon from '../common/LayoutIcon.vue';
import { generateContextMenuItems, type ContextMenuAction } from '@admin-core/layout';

const context = useLayoutContext();
const layoutComputed = useLayoutComputed();
const {
  tabs,
  activeKey,
  handleSelect,
  handleClose,
  handleCloseAll,
  handleCloseOther,
  handleCloseLeft,
  handleCloseRight,
  handleRefresh,
  handleToggleAffix,
  handleOpenInNewWindow,
  handleSort,
} = useTabsState();
const { collapsed: sidebarCollapsed } = useSidebarState();

// 配置
const tabbarConfig = computed(() => context.props.tabbar || {});
const styleType = computed(() => tabbarConfig.value.styleType || 'chrome');
const headerMode = computed(() => context.props.header?.mode || 'fixed');
const isHeaderFixed = computed(() => headerMode.value !== 'static');
const leftOffset = computed(() => layoutComputed.value.mainStyle.marginLeft || '0');
const panelRightOffset = computed(() => layoutComputed.value.mainStyle.marginRight || '0');

// 拖拽相关状态
const dragState = ref<{
  isDragging: boolean;
  dragIndex: number | null;
  dropIndex: number | null;
}>({
  isDragging: false,
  dragIndex: null,
  dropIndex: null,
});

// 最大化状态
const isMaximized = ref(false);

// 标签列表容器引用
const tabsContainerRef = ref<HTMLElement | null>(null);

// 标签元素引用
const tabRefs = new Map<string, HTMLElement>();
const setTabRef = (key: string) => (el: Element | ComponentPublicInstance | null) => {
  if (!el) {
    tabRefs.delete(key);
    return;
  }
  const node = el instanceof HTMLElement ? el : (el as ComponentPublicInstance).$el;
  if (node instanceof HTMLElement) {
    tabRefs.set(key, node);
  }
};

const flipPending = ref(false);
const flipPositions = ref(new Map<string, DOMRect>());

const recordTabPositions = () => {
  const map = new Map<string, DOMRect>();
  tabRefs.forEach((el, key) => {
    map.set(key, el.getBoundingClientRect());
  });
  flipPositions.value = map;
  flipPending.value = true;
};

const animateTabPositions = () => {
  if (!flipPending.value) return;
  const prevPositions = flipPositions.value;
  flipPending.value = false;
  const animated: HTMLElement[] = [];
  tabRefs.forEach((el, key) => {
    const prevRect = prevPositions.get(key);
    if (!prevRect) return;
    const nextRect = el.getBoundingClientRect();
    const dx = prevRect.left - nextRect.left;
    const dy = prevRect.top - nextRect.top;
    if (dx || dy) {
      el.style.transition = 'transform 0s';
      el.style.transform = `translate(${dx}px, ${dy}px)`;
      animated.push(el);
    }
  });
  if (!animated.length) return;
  requestAnimationFrame(() => {
    animated.forEach((el) => {
      el.style.transition = 'transform 300ms var(--admin-easing-default, cubic-bezier(0.4, 0, 0.2, 1))';
      el.style.transform = '';
    });
    window.setTimeout(() => {
      animated.forEach((el) => {
        el.style.transition = '';
      });
    }, 320);
  });
};

// 右键菜单
const contextMenuVisible = ref(false);
const contextMenuPosition = ref({ x: 0, y: 0 });
const contextMenuTargetKey = ref<string | null>(null);
const contextMenuRef = ref<HTMLElement | null>(null);

// 更多菜单
const moreMenuVisible = ref(false);
const moreMenuPosition = ref({ x: 0, y: 0 });
const moreMenuAnchorRef = ref<HTMLElement | null>(null);
const moreMenuRef = ref<HTMLElement | null>(null);

// 悬停状态
const hoveredKey = ref<string | null>(null);
const TAB_RENDER_CHUNK = 60;
const tabRenderCount = ref(TAB_RENDER_CHUNK);
const tabIndexMap = computed(() => {
  const map = new Map<string, number>();
  tabs.value.forEach((tab, index) => map.set(tab.key, index));
  return map;
});
const tabMap = computed(() => {
  const map = new Map<string, (typeof tabs.value)[0]>();
  tabs.value.forEach((tab) => map.set(tab.key, tab));
  return map;
});

// 类名
const tabbarClass = computed(() => [
  'layout-tabbar',
  `layout-tabbar--${styleType.value}`,
  {
    'layout-tabbar--with-sidebar': layoutComputed.value.showSidebar && !context.props.isMobile,
    'layout-tabbar--collapsed': sidebarCollapsed.value && !context.props.isMobile,
  },
]);

const visibleTabs = computed(() => tabs.value.slice(0, tabRenderCount.value));
const showScrollButtons = computed(() => canScrollLeft.value || canScrollRight.value);

// 样式
const tabbarStyle = computed(() => {
  const style: Record<string, string> = {
    height: `${layoutComputed.value.tabbarHeight}px`,
  };

  if (isHeaderFixed.value) {
    style.position = 'fixed';
    style.top = `${layoutComputed.value.headerHeight}px`;
    style.left = leftOffset.value;
    if (panelRightOffset.value !== '0') {
      style.right = panelRightOffset.value;
    }
  } else {
    style.position = 'static';
    if (leftOffset.value !== '0') {
      style.marginLeft = leftOffset.value;
    }
    if (panelRightOffset.value !== '0') {
      style.marginRight = panelRightOffset.value;
    }
    if (leftOffset.value !== '0' || panelRightOffset.value !== '0') {
      const leftValue = leftOffset.value !== '0' ? leftOffset.value : '0px';
      const rightValue = panelRightOffset.value !== '0' ? panelRightOffset.value : '0px';
      style.width = `calc(100% - ${leftValue} - ${rightValue})`;
    }
  }

  return style;
});

watch([tabs, activeKey], () => {
  const activeIndex = tabIndexMap.value.get(activeKey.value) ?? -1;
  if (activeIndex >= 0) {
    tabRenderCount.value = Math.min(tabs.value.length, Math.max(TAB_RENDER_CHUNK, activeIndex + 1));
  } else {
    tabRenderCount.value = Math.min(TAB_RENDER_CHUNK, tabs.value.length);
  }
}, { immediate: true });

watch(tabs, () => {
  animateTabPositions();
}, { flush: 'post' });

watchEffect((onCleanup) => {
  if (tabRenderCount.value >= tabs.value.length) return;
  const frame = requestAnimationFrame(() => {
    tabRenderCount.value = Math.min(tabRenderCount.value + TAB_RENDER_CHUNK, tabs.value.length);
  });
  onCleanup(() => cancelAnimationFrame(frame));
});

// 滚动状态
const canScrollLeft = ref(false);
const canScrollRight = ref(false);
const updateScrollState = () => {
  const container = tabsContainerRef.value;
  if (!container) {
    canScrollLeft.value = false;
    canScrollRight.value = false;
    return;
  }
  const { scrollLeft, scrollWidth, clientWidth } = container;
  canScrollLeft.value = scrollLeft > 0;
  canScrollRight.value = scrollLeft + clientWidth < scrollWidth - 1;
};

const scrollTabsBy = (direction: number) => {
  const container = tabsContainerRef.value;
  if (!container) return;
  const offset = Math.max(container.clientWidth * 0.6, 120);
  container.scrollBy({ left: offset * direction, behavior: 'smooth' });
  requestAnimationFrame(updateScrollState);
};

watch([tabs, tabRenderCount], () => {
  void nextTick(updateScrollState);
}, { immediate: true });

watch(activeKey, () => {
  void nextTick(() => {
    const el = tabRefs.get(activeKey.value);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', inline: 'center', block: 'nearest' });
    }
  });
});

onMounted(() => {
  window.addEventListener('resize', updateScrollState);
});

onUnmounted(() => {
  window.removeEventListener('resize', updateScrollState);
});

// 处理标签点击
const onTabClick = (key: string) => {
  handleSelect(key);
};

const onTabMouseEnter = (key: string) => {
  if (hoveredKey.value !== key) {
    hoveredKey.value = key;
  }
};

const onTabMouseLeave = () => {
  if (hoveredKey.value !== null) {
    hoveredKey.value = null;
  }
};

// 处理标签关闭
const onTabClose = (e: Event, key: string) => {
  e.stopPropagation();
  handleClose(key);
};

// 处理右键菜单
const onContextMenu = (e: MouseEvent, key: string) => {
  e.preventDefault();
  contextMenuTargetKey.value = key;
  contextMenuPosition.value = { x: e.clientX, y: e.clientY };
  contextMenuVisible.value = true;
  moreMenuVisible.value = false;
};

// 关闭右键菜单
const closeContextMenu = () => {
  contextMenuVisible.value = false;
  contextMenuTargetKey.value = null;
};

const closeMoreMenu = () => {
  moreMenuVisible.value = false;
};

const openMoreMenu = () => {
  if (!moreMenuAnchorRef.value) return;
  const rect = moreMenuAnchorRef.value.getBoundingClientRect();
  moreMenuPosition.value = {
    x: rect.left,
    y: rect.bottom + 6,
  };
  moreMenuVisible.value = !moreMenuVisible.value;
  contextMenuVisible.value = false;
};

const clampMenuPosition = (position: { x: number; y: number }, el: HTMLElement | null) => {
  if (!el || typeof window === 'undefined') return position;
  const margin = 8;
  const rect = el.getBoundingClientRect();
  let x = position.x;
  let y = position.y;
  const maxX = window.innerWidth - rect.width - margin;
  const maxY = window.innerHeight - rect.height - margin;
  if (rect.left < margin) x = margin;
  if (rect.right > window.innerWidth - margin) x = Math.max(margin, maxX);
  if (rect.top < margin) y = margin;
  if (rect.bottom > window.innerHeight - margin) y = Math.max(margin, maxY);
  return { x, y };
};

watch(
  () => contextMenuVisible.value,
  async (visible) => {
    if (!visible) return;
    await nextTick();
    contextMenuPosition.value = clampMenuPosition(contextMenuPosition.value, contextMenuRef.value);
  }
);

watch(
  () => moreMenuVisible.value,
  async (visible) => {
    if (!visible) return;
    await nextTick();
    moreMenuPosition.value = clampMenuPosition(moreMenuPosition.value, moreMenuRef.value);
  }
);

const handleMenuAction = (action: ContextMenuAction, targetKey: string | null) => {
  if (!targetKey) return;
  switch (action) {
    case 'refresh':
      handleRefresh(targetKey);
      break;
    case 'close':
      handleClose(targetKey);
      break;
    case 'closeOther':
      handleCloseOther(targetKey);
      break;
    case 'closeLeft':
      handleCloseLeft(targetKey);
      break;
    case 'closeRight':
      handleCloseRight(targetKey);
      break;
    case 'closeAll':
      handleCloseAll();
      break;
    case 'pin':
    case 'unpin':
      handleToggleAffix(targetKey);
      break;
    case 'openInNewWindow':
      handleOpenInNewWindow(targetKey);
      break;
    case 'maximize':
      if (!isMaximized.value) {
        if (targetKey !== activeKey.value) {
          handleSelect(targetKey);
        }
        toggleMaximize();
      }
      break;
    case 'restoreMaximize':
      if (isMaximized.value) toggleMaximize();
      break;
    default:
      break;
  }
};

const contextMenuItems = computed(() => {
  const key = contextMenuTargetKey.value;
  if (!key) return [];
  const tab = tabMap.value.get(key);
  if (!tab) return [];
  const items = generateContextMenuItems(
    tab,
    tabs.value,
    activeKey.value,
    context.t,
    tabIndexMap.value,
    { isMaximized: isMaximized.value }
  );
  return items.filter((item) => {
    if (item.key === 'maximize' || item.key === 'restoreMaximize') {
      return tabbarConfig.value.showMaximize !== false;
    }
    return true;
  });
});

const moreMenuItems = computed(() => {
  const key = activeKey.value || tabs.value[0]?.key || '';
  if (!key) return [];
  const tab = tabMap.value.get(key);
  if (!tab) return [];
  const items = generateContextMenuItems(
    tab,
    tabs.value,
    activeKey.value,
    context.t,
    tabIndexMap.value,
    { isMaximized: isMaximized.value }
  );
  return items.filter((item) => {
    if (item.key === 'maximize' || item.key === 'restoreMaximize') {
      return tabbarConfig.value.showMaximize !== false;
    }
    return true;
  });
});

const getTabTitle = (tab: typeof tabs.value[0]) => {
  const meta = tab.meta as Record<string, unknown> | undefined;
  const title = (meta?.newTabTitle as string | undefined) || (meta?.title as string | undefined) || tab.name;
  return context.t(title);
};

// ==================== 拖拽排序功能 ====================
const onDragStart = (e: DragEvent, index: number) => {
  if (!tabbarConfig.value.draggable) return;
  const tab = tabs.value[index];
  if (tab?.affix) {
    e.preventDefault();
    return;
  }
  dragState.value = {
    isDragging: true,
    dragIndex: index,
    dropIndex: null,
  };
  if (e.dataTransfer) {
    e.dataTransfer.effectAllowed = 'move';
    e.dataTransfer.setData('text/plain', String(index));
  }
};

const onDragOver = (e: DragEvent, index: number) => {
  if (!tabbarConfig.value.draggable || !dragState.value.isDragging) return;
  e.preventDefault();
  const tab = tabs.value[index];
  if (tab?.affix) return;
  const fromIndex = dragState.value.dragIndex;
  dragState.value.dropIndex = index;
  if (fromIndex === null || fromIndex === index) return;
  const targetKey = tab.key;
  const targetEl = tabRefs.get(targetKey);
  if (!targetEl) return;
  const rect = targetEl.getBoundingClientRect();
  const midpoint = rect.left + rect.width / 2;
  const shouldMove =
    (fromIndex < index && e.clientX > midpoint) ||
    (fromIndex > index && e.clientX < midpoint);
  if (!shouldMove) return;
  recordTabPositions();
  handleSort(fromIndex, index);
  dragState.value.dragIndex = index;
};

const onDragLeave = () => {
  dragState.value.dropIndex = null;
};

const onDrop = (e: DragEvent, toIndex: number) => {
  if (!tabbarConfig.value.draggable) return;
  e.preventDefault();
  const fromIndex = dragState.value.dragIndex;
  if (fromIndex !== null && fromIndex !== toIndex) {
    const targetTab = tabs.value[toIndex];
    if (!targetTab?.affix) {
      recordTabPositions();
      handleSort(fromIndex, toIndex);
    }
  }
  dragState.value = {
    isDragging: false,
    dragIndex: null,
    dropIndex: null,
  };
};

const onDragEnd = () => {
  dragState.value = {
    isDragging: false,
    dragIndex: null,
    dropIndex: null,
  };
};

// ==================== 中键关闭功能 ====================
const onMouseDown = (e: MouseEvent, tab: typeof tabs.value[0]) => {
  if (e.button === 1 && tabbarConfig.value.middleClickToClose !== false) {
    e.preventDefault();
    if (tab.closable !== false && !tab.affix) {
      handleClose(tab.key);
    }
  }
};

// ==================== 滚轮滚动 ====================
const onWheel = (e: WheelEvent) => {
  if (!tabbarConfig.value.wheelable) return;
  const container = tabsContainerRef.value;
  if (!container) return;
  if (container.scrollWidth <= container.clientWidth) return;
  e.preventDefault();
  const delta = Math.abs(e.deltaY) > Math.abs(e.deltaX) ? e.deltaY : e.deltaX;
  container.scrollLeft += delta;
  updateScrollState();
};

// ==================== 最大化功能 ====================
const toggleMaximize = () => {
  isMaximized.value = !isMaximized.value;
  context.events?.onTabMaximize?.(isMaximized.value);
  if (isMaximized.value) {
    document.body.classList.add('layout-content-maximized');
    document.body.dataset.contentMaximized = 'true';
  } else {
    document.body.classList.remove('layout-content-maximized');
    delete document.body.dataset.contentMaximized;
  }
};

const handleKeyDown = (e: KeyboardEvent) => {
  if (e.key === 'Escape') {
    toggleMaximize();
  }
};

const syncKeydownListener = (enabled: boolean) => {
  document.removeEventListener('keydown', handleKeyDown);
  if (enabled) {
    document.addEventListener('keydown', handleKeyDown);
  }
};

watch(isMaximized, (value) => {
  syncKeydownListener(value);
}, { immediate: true });

onUnmounted(() => {
  syncKeydownListener(false);
  document.body.classList.remove('layout-content-maximized');
  delete document.body.dataset.contentMaximized;
});
</script>

<template>
  <div
    :class="tabbarClass"
    :style="tabbarStyle"
    :data-with-sidebar="layoutComputed.showSidebar && !context.props.isMobile ? 'true' : undefined"
    :data-collapsed="sidebarCollapsed && !context.props.isMobile ? 'true' : undefined"
    :data-style="styleType"
    @click="() => { closeContextMenu(); closeMoreMenu(); }"
  >
    <div class="layout-tabbar__inner flex h-full">
      <!-- 左侧插槽 -->
      <div v-if="$slots.left" class="layout-tabbar__left shrink-0 px-2">
        <slot name="left" />
      </div>

      <!-- 左侧滚动按钮 -->
      <button
        v-if="showScrollButtons"
        type="button"
        class="layout-tabbar__scroll-btn layout-tabbar__scroll-btn--left"
        :data-disabled="canScrollLeft ? 'false' : 'true'"
        :disabled="!canScrollLeft"
        @click.stop="canScrollLeft && scrollTabsBy(-1)"
      >
        <LayoutIcon name="tabbar-scroll-left" size="sm" />
      </button>

      <!-- 标签列表 -->
      <div
        ref="tabsContainerRef"
        class="layout-tabbar__tabs layout-scroll-container flex h-full flex-1 overflow-x-auto scrollbar-none"
        :data-dragging="dragState.isDragging ? 'true' : undefined"
        @wheel="onWheel"
        @scroll="updateScrollState"
      >
        <slot>
          <div
            v-for="(tab, index) in visibleTabs"
            :key="tab.key"
            :ref="setTabRef(tab.key)"
            :class="[
              'data-active:text-primary',
              'group',
              'layout-tabbar__tab',
              `layout-tabbar__tab--${styleType}`,
              {
                'layout-tabbar__tab--active': tab.key === activeKey,
                'layout-tabbar__tab--affix': !!tab.affix,
                'layout-tabbar__tab--dragging': dragState.isDragging && dragState.dragIndex === index,
                'layout-tabbar__tab--drop-target': dragState.isDragging && dragState.dropIndex === index,
              },
            ]"
            :data-index="index"
            :data-state="tab.key === activeKey ? 'active' : 'inactive'"
            :data-style="styleType"
            :data-hovered="hoveredKey === tab.key ? 'true' : undefined"
            :data-affix="tab.affix ? 'true' : undefined"
            :data-dragging="dragState.isDragging && dragState.dragIndex === index ? 'true' : undefined"
            :data-drop-target="dragState.isDragging && dragState.dropIndex === index ? 'true' : undefined"
            :draggable="tabbarConfig.draggable && !tab.affix"
            @click="onTabClick(tab.key)"
            @contextmenu="onContextMenu($event, tab.key)"
            @mouseenter="onTabMouseEnter(tab.key)"
            @mouseleave="onTabMouseLeave"
            @mousedown="onMouseDown($event, tab)"
            @dragstart="onDragStart($event, index)"
            @dragover="onDragOver($event, index)"
            @dragleave="onDragLeave"
            @drop="onDrop($event, index)"
            @dragend="onDragEnd"
          >
            <template v-if="styleType === 'chrome'">
              <div class="layout-tabbar__chrome">
                <div class="layout-tabbar__chrome-divider" />
                <div class="layout-tabbar__chrome-bg">
                  <div class="layout-tabbar__chrome-bg-content" />
                  <svg class="layout-tabbar__chrome-bg-before" height="7" width="7" viewBox="0 0 7 7">
                    <path d="M 0 7 A 7 7 0 0 0 7 0 L 7 7 Z" />
                  </svg>
                  <svg class="layout-tabbar__chrome-bg-after" height="7" width="7" viewBox="0 0 7 7">
                    <path d="M 0 0 A 7 7 0 0 0 7 7 L 0 7 Z" />
                  </svg>
                </div>
                <div class="layout-tabbar__chrome-main">
                  <!-- 图标 -->
                  <span v-if="tabbarConfig.showIcon && tab.icon" class="layout-tabbar__tab-icon">
                    <slot name="tab-icon" :tab="tab">
                      <span class="text-sm">{{ tab.icon }}</span>
                    </slot>
                  </span>

                  <!-- 名称 -->
                  <span class="layout-tabbar__tab-name truncate">
                    {{ getTabTitle(tab) }}
                  </span>
                </div>
                <div class="layout-tabbar__chrome-extra">
                  <!-- 固定图标 -->
                  <button
                    v-if="tab.affix"
                    type="button"
                    class="layout-tabbar__tab-pin"
                    @click.stop="handleToggleAffix(tab.key)"
                  >
                    <LayoutIcon name="tabbar-pin" size="xs" />
                  </button>

                  <!-- 关闭按钮 -->
                  <button
                    v-if="tab.closable !== false && !tab.affix"
                    type="button"
                    class="layout-tabbar__tab-close"
                    @click="onTabClose($event, tab.key)"
                  >
                    <LayoutIcon name="tabbar-close" size="xs" />
                  </button>
                </div>
              </div>
            </template>
            <template v-else>
              <div class="layout-tabbar__tab-content">
                <div class="layout-tabbar__tab-extra">
                  <!-- 关闭按钮 -->
                  <button
                    v-if="tab.closable !== false && !tab.affix"
                    type="button"
                    class="layout-tabbar__tab-close"
                    @click="onTabClose($event, tab.key)"
                  >
                    <LayoutIcon name="tabbar-close" size="xs" />
                  </button>

                  <!-- 固定图标 -->
                  <button
                    v-if="tab.affix"
                    type="button"
                    class="layout-tabbar__tab-pin"
                    @click.stop="handleToggleAffix(tab.key)"
                  >
                    <LayoutIcon name="tabbar-pin" size="xs" />
                  </button>
                </div>
                <div class="layout-tabbar__tab-main">
                  <!-- 图标 -->
                  <span v-if="tabbarConfig.showIcon && tab.icon" class="layout-tabbar__tab-icon">
                    <slot name="tab-icon" :tab="tab">
                      <span class="text-sm">{{ tab.icon }}</span>
                    </slot>
                  </span>

                  <!-- 名称 -->
                  <span class="layout-tabbar__tab-name truncate">
                    {{ getTabTitle(tab) }}
                  </span>
                </div>
              </div>
            </template>
          </div>
        </slot>
      </div>

      <!-- 右侧滚动按钮 -->
      <button
        v-if="showScrollButtons"
        type="button"
        class="layout-tabbar__scroll-btn layout-tabbar__scroll-btn--right"
        :data-disabled="canScrollRight ? 'false' : 'true'"
        :disabled="!canScrollRight"
        @click.stop="canScrollRight && scrollTabsBy(1)"
      >
        <LayoutIcon name="tabbar-scroll-right" size="sm" />
      </button>

      <!-- 右侧插槽 -->
      <div v-if="$slots.right" class="layout-tabbar__right shrink-0 px-2">
        <slot name="right" />
      </div>

      <!-- 最大化按钮 -->
      <button
        v-if="tabbarConfig.showMaximize"
        type="button"
        class="layout-tabbar__tool-btn"
        :title="isMaximized ? context.t('layout.tabbar.restore') : context.t('layout.tabbar.maximize')"
        @click.stop="toggleMaximize"
      >
        <LayoutIcon v-if="!isMaximized" name="tabbar-maximize" size="sm" />
        <LayoutIcon v-else name="tabbar-restore" size="sm" />
      </button>

      <!-- 更多操作 -->
      <div v-if="tabbarConfig.showMore !== false" class="layout-tabbar__more">
        <slot name="extra">
          <button
            ref="moreMenuAnchorRef"
            type="button"
            class="layout-tabbar__tool-btn"
            :title="context.t('layout.common.more')"
            @click.stop="openMoreMenu"
          >
            <LayoutIcon name="tabbar-more" size="sm" />
          </button>
        </slot>
      </div>
    </div>

    <!-- 右键菜单 -->
    <Teleport to="body">
      <div
        v-if="contextMenuVisible"
        ref="contextMenuRef"
        class="layout-tabbar__context-menu fixed z-layout-overlay min-w-40 rounded-md border border-border py-1 shadow-lg"
        :style="{ left: `${contextMenuPosition.x}px`, top: `${contextMenuPosition.y}px` }"
      >
        <template v-for="item in contextMenuItems" :key="item.key">
          <div v-if="item.divider" class="my-1 h-px bg-border" />
          <button
            v-else
            type="button"
            class="layout-tabbar__menu-item flex w-full items-center px-3 py-1.5 text-sm disabled:cursor-not-allowed disabled:opacity-50"
            :disabled="item.disabled"
            @click="() => { handleMenuAction(item.key, contextMenuTargetKey); closeContextMenu(); }"
          >
            {{ item.label }}
          </button>
        </template>
      </div>
    </Teleport>

    <!-- 点击空白关闭菜单的遮罩 -->
    <Teleport to="body">
      <div
        v-if="contextMenuVisible"
        class="fixed inset-0 z-layout-overlay"
        @click="closeContextMenu"
      />
    </Teleport>

    <!-- 更多菜单 -->
    <Teleport to="body">
      <div
        v-if="moreMenuVisible"
        ref="moreMenuRef"
        class="layout-tabbar__more-menu fixed z-layout-overlay min-w-40 rounded-md border border-border py-1 shadow-lg"
        :style="{ left: `${moreMenuPosition.x}px`, top: `${moreMenuPosition.y}px` }"
      >
        <template v-for="item in moreMenuItems" :key="item.key">
          <div v-if="item.divider" class="my-1 h-px bg-border" />
          <button
            v-else
            type="button"
            class="layout-tabbar__menu-item flex w-full items-center px-3 py-1.5 text-sm disabled:cursor-not-allowed disabled:opacity-50"
            :disabled="item.disabled"
            @click="() => { handleMenuAction(item.key, activeKey || tabs[0]?.key || null); closeMoreMenu(); }"
          >
            {{ item.label }}
          </button>
        </template>
      </div>
    </Teleport>

    <Teleport to="body">
      <div
        v-if="moreMenuVisible"
        class="fixed inset-0 z-layout-overlay"
        @click="closeMoreMenu"
      />
    </Teleport>
  </div>
</template>

<style>
/* 样式已在核心 CSS 中定义 */
</style>
