// packages/layout/vue/src/components/layout/LayoutOverlay.vue
<script setup lang="ts">
/**
 * 遮罩层组件（移动端侧边栏展开时显示）
 */
import { computed } from 'vue';
import { useLayoutContext, useSidebarState } from '../../composables';

const context = useLayoutContext();
const { collapsed } = useSidebarState();

// 是否显示遮罩
const visible = computed(() => context.props.isMobile && !collapsed.value);

// 点击遮罩关闭侧边栏
const handleClick = () => {
  context.toggleSidebarCollapse();
};
</script>

<template>
  <Teleport to="body">
    <Transition name="fade">
      <div
        v-if="visible"
        class="layout-overlay layout-overlay--visible"
        data-state="visible"
        @click="handleClick"
      />
    </Transition>
  </Teleport>
</template>

<style>
/* 样式已在核心 CSS 中定义 */
</style>

// packages/layout/react/src/components/layout/LayoutOverlay.tsx
/**
 * 遮罩层组件（移动端侧边栏展开时显示）
 */

import { memo } from 'react';
import { createPortal } from 'react-dom';
import { useLayoutContext } from '../../hooks';
import { useSidebarState } from '../../hooks/use-layout-state';

export const LayoutOverlay = memo(function LayoutOverlay() {
  const context = useLayoutContext();
  const { collapsed, toggle } = useSidebarState();

  // 是否显示遮罩
  const visible = context.props.isMobile && !collapsed;

  if (!visible) return null;

  return createPortal(
    <div
      className="layout-overlay layout-overlay--visible"
      data-state="visible"
      onClick={toggle}
    />,
    document.body
  );
});
