// packages/layout/vue/src/components/layout/LayoutPanel.vue
<script setup lang="ts">
/**
 * 功能区组件
 */
import { computed } from 'vue';
import { useLayoutContext, useLayoutComputed, usePanelState } from '../../composables';

const context = useLayoutContext();
const layoutComputed = useLayoutComputed();
const { collapsed, width, position, toggle } = usePanelState();

// 配置
const panelConfig = computed(() => context.props.panel || {});

// 是否显示折叠按钮
const showCollapseButton = computed(() => 
  panelConfig.value.collapsedButton !== false && 
  context.props.disabled?.panelCollapseButton !== true
);

// 类名
const panelClass = computed(() => [
  'layout-panel',
  `layout-panel--${position.value}`,
  {
    'layout-panel--collapsed': collapsed.value,
  },
]);

// 样式
const panelStyle = computed(() => ({
  width: `${width.value}px`,
  top: `${layoutComputed.value.headerHeight}px`,
}));
</script>

<template>
  <aside
    :class="panelClass"
    :style="panelStyle"
    :data-position="position"
    :data-collapsed="collapsed ? 'true' : undefined"
  >
    <div class="layout-panel__inner flex h-full flex-col">
      <!-- 头部 -->
      <div v-if="$slots.header || showCollapseButton" class="layout-panel__header flex shrink-0 items-center justify-between border-b border-border px-4 py-3">
        <slot name="header">
          <span class="font-medium">{{ context.t('layout.panel.title') }}</span>
        </slot>
        
        <!-- 折叠按钮 -->
        <button
          v-if="showCollapseButton"
          type="button"
          class="flex h-7 w-7 items-center justify-center rounded transition-colors hover:bg-black/5"
          :title="collapsed ? context.t('layout.panel.expand') : context.t('layout.panel.collapse')"
          @click="toggle"
        >
          <svg
            class="h-4 w-4 transition-transform duration-layout-normal"
            :class="{ 'rotate-180': position === 'left' ? !collapsed : collapsed }"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
          >
            <path d="M15 18l-6-6 6-6" />
          </svg>
        </button>
      </div>

      <!-- 内容 -->
      <div class="layout-panel__content layout-scroll-container flex-1 overflow-y-auto overflow-x-hidden p-4">
        <slot />
      </div>

      <!-- 底部 -->
      <div v-if="$slots.footer" class="layout-panel__footer shrink-0 border-t border-border px-4 py-3">
        <slot name="footer" />
      </div>
    </div>
  </aside>
</template>

<style>
/* 样式已在核心 CSS 中定义 */
</style>

// packages/layout/react/src/components/layout/LayoutPanel.tsx
/**
 * 功能区组件
 */

import { memo, useMemo, type ReactNode } from 'react';
import { useLayoutContext, useLayoutComputed } from '../../hooks';
import { usePanelState } from '../../hooks/use-layout-state';

export interface LayoutPanelProps {
  children?: ReactNode;
  header?: ReactNode;
  footer?: ReactNode;
}

export const LayoutPanel = memo(function LayoutPanel({ children, header, footer }: LayoutPanelProps) {
  const context = useLayoutContext();
  const computed = useLayoutComputed();
  const { collapsed, width, position, toggle } = usePanelState();

  const panelConfig = context.props.panel || {};

  // 是否显示折叠按钮
  const showCollapseButton =
    panelConfig.collapsedButton !== false &&
    context.props.disabled?.panelCollapseButton !== true;

  // 类名
  const panelClassName = useMemo(() => {
    const classes = ['layout-panel', `layout-panel--${position}`];
    if (collapsed) classes.push('layout-panel--collapsed');
    return classes.join(' ');
  }, [position, collapsed]);

  // 样式
  const panelStyle = useMemo(() => ({
    width: `${width}px`,
    top: `${computed.headerHeight}px`,
  }), [width, computed.headerHeight]);

  return (
    <aside
      className={panelClassName}
      style={panelStyle}
      data-position={position}
      data-collapsed={collapsed ? 'true' : undefined}
    >
      <div className="layout-panel__inner flex h-full flex-col">
        {/* 头部 */}
        {(header || showCollapseButton) && (
          <div className="layout-panel__header flex shrink-0 items-center justify-between border-b border-border px-4 py-3">
            {header || <span className="font-medium">{context.t('layout.panel.title')}</span>}

            {/* 折叠按钮 */}
            {showCollapseButton && (
              <button
                type="button"
                className="flex h-7 w-7 items-center justify-center rounded transition-colors hover:bg-black/5"
                title={
                  collapsed
                    ? context.t('layout.panel.expand')
                    : context.t('layout.panel.collapse')
                }
                onClick={toggle}
              >
                <svg
                  className={`h-4 w-4 transition-transform duration-200 ${
                    position === 'left' ? (!collapsed ? 'rotate-180' : '') : collapsed ? 'rotate-180' : ''
                  }`}
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                >
                  <path d="M15 18l-6-6 6-6" />
                </svg>
              </button>
            )}
          </div>
        )}

        {/* 内容 */}
        <div className="layout-panel__content layout-scroll-container flex-1 overflow-y-auto overflow-x-hidden p-4">
          {children}
        </div>

        {/* 底部 */}
        {footer && (
          <div className="layout-panel__footer shrink-0 border-t border-border px-4 py-3">
            {footer}
          </div>
        )}
      </div>
    </aside>
  );
});
