// examples/vue-demo/src/views/components/table/CustomCell.vue
<script setup lang="ts">
import type { VxeTableGridOptions } from '@admin-core/table-vue';

import { useAdminTable } from '@admin-core/table-vue';

import { fetchProductRows, type DemoProductRow } from './data';

const statusOptions = [
  { color: '#16a34a', label: 'Enabled', value: 'enabled' },
  { color: '#dc2626', label: 'Disabled', value: 'disabled' },
];
const statusSelectOptions = [
  { label: 'Enabled', value: 'enabled' },
  { label: 'Disabled', value: 'disabled' },
];

const gridOptions: VxeTableGridOptions<DemoProductRow> = {
  columns: [
    { title: '序号', type: 'seq', width: 60 },
    { field: 'category', title: 'Category', width: 100 },
    { field: 'imageUrl', slots: { default: 'image' }, title: 'Image', width: 100 },
    { field: 'open', slots: { default: 'openSwitch' }, title: 'Switch(Slot)', width: 140 },
    {
      cellRender: {
        name: 'CellSwitch',
        props: {
          checkedValue: 1,
          uncheckedValue: 0,
        },
      },
      field: 'open',
      title: 'CellSwitch',
      width: 120,
    },
    { field: 'open', slots: { default: 'openCheckbox' }, title: 'Checkbox(Slot)', width: 150 },
    { field: 'status', slots: { default: 'statusSelect' }, title: 'Select(Slot)', width: 150 },
    {
      cellRender: {
        name: 'CellTag',
        options: statusOptions,
      },
      field: 'status',
      title: 'Status',
      width: 120,
    },
    { field: 'color', title: 'Color', width: 100 },
    { field: 'productName', slots: { default: 'nameInput' }, title: 'Input(Slot)', width: 220 },
    { field: 'price', title: 'Price', width: 100 },
    { field: 'releaseDate', formatter: 'formatDateTime', title: 'Date', width: 200 },
    {
      cellRender: {
        attrs: {
          nameField: 'productName',
          onClick: ({ code, row }: any) => {
            console.log('action click:', code, row.productName);
          },
        },
        name: 'CellOperation',
      },
      field: 'operation',
      fixed: 'right',
      title: '操作',
      width: 180,
    },
  ],
  keepSource: true,
  proxyConfig: {
    ajax: {
      query: async ({ page }) =>
        await fetchProductRows({
          page: page.currentPage,
          pageSize: page.pageSize,
        }),
    },
    autoLoad: true,
    enabled: true,
    response: {
      list: 'items',
      result: 'items',
      total: 'total',
    },
  },
};

const [Grid] = useAdminTable<DemoProductRow>({ gridOptions });
</script>

<template>
  <div class="page-container">
    <h1 class="page-title">表格 - 自定义单元格</h1>
    <p class="page-description">同时演示 Switch/Checkbox/Select/Input 插槽渲染与内置渲染器。</p>

    <div class="card">
      <Grid table-title="自定义单元格列表">
        <template #image="{ row }">
          <img :src="row.imageUrl" width="28" height="28" class="rounded-full" />
        </template>
        <template #openSwitch="{ row }">
          <vxe-switch
            v-model="row.open"
            :open-value="1"
            :close-value="0"
            size="small"
          />
        </template>
        <template #openCheckbox="{ row }">
          <vxe-checkbox
            v-model="row.open"
            :checked-value="1"
            :unchecked-value="0"
            content=""
          />
        </template>
        <template #statusSelect="{ row }">
          <vxe-select
            v-model="row.status"
            :options="statusSelectOptions"
            size="small"
            style="width: 132px"
          />
        </template>
        <template #nameInput="{ row }">
          <vxe-input
            v-model="row.productName"
            size="small"
            style="width: 160px"
          />
        </template>
      </Grid>
    </div>
  </div>
</template>

// examples/react-demo/src/pages/components/table/CustomCell.tsx
import { useAdminTable, type AntdGridOptions } from '@admin-core/table-react';
import { useMemo } from 'react';
import { Avatar, Button, Checkbox, Input, Select, Switch } from 'antd';

import { fetchProductRows, type DemoProductRow } from './data';

export default function TableCustomCell() {
  const [TableView] = useAdminTable<DemoProductRow>(
    useMemo(
      () => ({
        gridOptions: {
          columns: [
            { title: '序号', field: 'id', width: 120 },
            { field: 'category', title: 'Category', width: 120 },
            { field: 'imageUrl', slots: { default: 'image' }, title: 'Image', width: 120 },
            { field: 'open', slots: { default: 'openSwitch' }, title: 'Switch(Slot)', width: 140 },
            {
              cellRender: {
                name: 'CellSwitch',
                props: {
                  checkedValue: 1,
                  uncheckedValue: 0,
                },
              },
              field: 'open',
              title: 'CellSwitch',
              width: 120,
            },
            { field: 'open', slots: { default: 'openCheckbox' }, title: 'Checkbox(Slot)', width: 150 },
            { field: 'status', slots: { default: 'statusSelect' }, title: 'Select(Slot)', width: 160 },
            {
              cellRender: {
                name: 'CellTag',
                options: [
                  { color: 'success', label: 'Enabled', value: 'enabled' },
                  { color: 'error', label: 'Disabled', value: 'disabled' },
                ],
              },
              field: 'status',
              title: 'Status',
              width: 120,
            },
            { field: 'color', title: 'Color', width: 100 },
            { field: 'productName', slots: { default: 'nameInput' }, title: 'Input(Slot)', width: 220 },
            { field: 'price', title: 'Price', width: 100 },
            { field: 'releaseDate', title: 'Release Date', width: 200 },
            {
              cellRender: {
                attrs: {
                  nameField: 'productName',
                  onClick: ({ code, row }: any) => {
                    console.log('action click:', code, row.productName);
                  },
                },
                name: 'CellOperation',
              },
              field: 'operation',
              fixed: 'right',
              title: '操作',
              width: 180,
            },
          ],
          keepSource: true,
          proxyConfig: {
            ajax: {
              query: async ({ page }: any) =>
                await fetchProductRows({
                  page: page.currentPage,
                  pageSize: page.pageSize,
                }),
            },
            autoLoad: true,
            enabled: true,
            response: {
              list: 'items',
              result: 'items',
              total: 'total',
            },
          },
        } as AntdGridOptions<DemoProductRow>,
      }),
      []
    )
  );

  return (
    <div className="page-container">
      <h1 className="page-title">表格 - 自定义单元格</h1>
      <p className="page-description">同时演示 Switch/Checkbox/Select/Input 插槽渲染与内置渲染器。</p>

      <div className="card">
        <TableView
          tableTitle="自定义单元格列表"
          slots={{
            image: ({ row }: any) => <Avatar size={28} src={row.imageUrl} />,
            openSwitch: ({ row }: any) => (
              <Switch
                defaultChecked={row.open === 1}
                size="small"
                onChange={(next) => {
                  console.log('switch change:', row.productName, next);
                }}
              />
            ),
            openCheckbox: ({ row }: any) => (
              <Checkbox
                defaultChecked={row.open === 1}
                onChange={(event) => {
                  console.log('checkbox change:', row.productName, event.target.checked);
                }}
              />
            ),
            statusSelect: ({ row }: any) => (
              <Select
                defaultValue={row.status}
                options={[
                  { label: 'Enabled', value: 'enabled' },
                  { label: 'Disabled', value: 'disabled' },
                ]}
                size="small"
                style={{ width: 132 }}
                onChange={(value) => {
                  console.log('select change:', row.productName, value);
                }}
              />
            ),
            nameInput: ({ row }: any) => (
              <Input
                defaultValue={row.productName}
                size="small"
                style={{ width: 160 }}
                onChange={(event) => {
                  console.log('input change:', row.productName, event.target.value);
                }}
              />
            ),
            action: () => <Button type="link">编辑</Button>,
          }}
        />
      </div>
    </div>
  );
}
